###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Alexa
#   @description    :   Alexa automations.
###############################################################################

emulated_hue:
  host_ip: 192.168.3.2
  listen_port: 80
  expose_by_default: false
  off_maps_to_on_domains:
    - script
    - scene
  exposed_domains:
    - scene
    - automation
    - script
    - climate
    - light
  entities:
    light.wall_ambient:
      name: "Wall Light"
      hidden: false
    scene.kitchen_ambient:
      name: "Kitchen Ambient"
      hidden: false
    scene.closet_off:
      name: "Bedroom Fan"
      hidden: false
    scene.closet_on:
      name: "Closet"
      hidden: false
    script.play_last_message:
      name: "Repite Last Message"
      hidden: false

sensor:
  - platform: history_stats
    name: Echo Runtime Month
    unique_id: echos_runtime
    entity_id: group.all_echos
    state: "on"
    type: time
    end: "{{ now().replace(hour=9, minute=0, second=0) }}"
    duration:
      hours: 730

group:
  all_echos:
    - media_player.portable_echo

template:
  - sensor:
      - name: alexa_audio
        state: >-
          {%- if is_state('sensor.last_alexa', 'media_player.livingroom_echo') %}
            living_room
          {% elif is_state('sensor.last_alexa', 'media_player.kitchen_echo') %}
            kitchen
          {% elif is_state('sensor.last_alexa', 'media_player.portable_echo') %}
            bedroom
          {% elif is_state('sensor.last_alexa', 'media_player.bathroom_echo') %}
            bathroom
          {% else %}
            backyard
          {%- endif %}
      - name: last_alexa
        state: >
          {{ expand('group.all_echos') | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}

automation:
  - id: e1cb17ea-0423-11eb-adc1-0242ac120002
    alias: Set Last Alexa Called Time
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - group.all_echos
    action:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.last_time_alexa_called
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
