###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   BirdNet-Go
#   @description    :   A Collection of Notification Scripts and Configs.
###############################################################################

template:
  - trigger:
      - platform: mqtt
        topic: "birdnet"
      - platform: time
        at: "00:00:00"
        id: reset
    sensor:
      - unique_id: c893533c-3c06-4ebe-a5bb-da833da0a947
        name: BirdNET-Go Events
        state: "{{ today_at(trigger.payload_json.Time) }}"
        attributes:
          bird_events: >
            {% if trigger.id == 'reset' %}
              {{ [] }}
            {% else %}
              {% set time = trigger.payload_json.Time %}
              {% set name = trigger.payload_json.CommonName %}
              {% set confidence = trigger.payload_json.Confidence|round(2) * 100 ~ '%' %}
              {% set current = this.attributes.get('bird_events', []) %}
              {% set new = dict(time=time, name=name, confidence=confidence) %}
              {{ current + [new] }}
            {% endif %}

automation:
  - alias: Store Bird Data to Database
    trigger:
      - platform: state
        entity_id: sensor.birdnet_go_events
    action:
      service: python_script.store_bird_data
      data:
        time: "{{ state_attr('sensor.birdnet_go_events', 'time') }}"
        birdName: "{{ state_attr('sensor.birdnet_go_events', 'name') }}"
        eventCount: "{{ state_attr('sensor.birdnet_go_events', 'eventCount') }}"
        confidence: "{{ state_attr('sensor.birdnet_go_events', 'confidence') }}"
