###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Kitchen
#   @description    :   Kitchen Automations.
###############################################################################

timer:
  cooking_timer:
    name: "Cooking Timer"
    duration: "01:00:00"
    icon: mdi:timer
    restore: true

input_boolean:
  cooking_mode:
    name: "Cooking Mode"
    icon: mdi:message-bulleted

sensor:
  - platform: rest
    resource: "http://192.168.3.10:9925/api/groups/mealplans/today"
    method: GET
    name: Mealie todays meal
    headers:
      Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb25nX3Rva2VuIjp0cnVlLCJpZCI6IjFlYmMyNjRiLWY5M2UtNDU2Yy1hNjExLTdiMzIzMjE1MDQ3YyIsIm5hbWUiOiJob21lYXNzaXN0YW50IiwiaW50ZWdyYXRpb25faWQiOiJnZW5lcmljIiwiZXhwIjoxODY4NDQ4NDg4fQ.IfIqJwhnjfAQPe5jMaHGeYP7-s1nsHCPAr-sI2STyJQ
    value_template: "{{ value_json[0].recipe.name }}"
    force_update: true
    scan_interval: 30
  - platform: rest
    resource: "http://192.168.3.10:9925/api/groups/mealplans/today"
    method: GET
    name: Mealie todays meal ID
    headers:
      Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb25nX3Rva2VuIjp0cnVlLCJpZCI6IjFlYmMyNjRiLWY5M2UtNDU2Yy1hNjExLTdiMzIzMjE1MDQ3YyIsIm5hbWUiOiJob21lYXNzaXN0YW50IiwiaW50ZWdyYXRpb25faWQiOiJnZW5lcmljIiwiZXhwIjoxODY4NDQ4NDg4fQ.IfIqJwhnjfAQPe5jMaHGeYP7-s1nsHCPAr-sI2STyJQ
    value_template: "{{ value_json[0].recipe.id }}"
    force_update: true
    scan_interval: 30

automation:
  - id: b668f047-c409-4bec-a12a-537b615038e4
    alias: Notification - Cooking Complete
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.careli_maf01_68e5_air_fryer
        from: cooking
        to: shutdown
      - platform: state
        entity_id:
          - sensor.careli_maf01_68e5_air_fryer
        from: cooking
        to: standby
      - platform: state
        entity_id:
          - sensor.careli_maf01_68e5_air_fryer
        to: cooked
        from: cooking
      - platform: state
        entity_id:
          - sensor.chunmi_n23l01_bcf8_oven
        from: cooking
        to: cook finish
      - platform: state
        entity_id:
          - sensor.chunmi_eh3_e09c_cooker
        from: running
        to: keepwarm
      - platform: state
        entity_id:
          - sensor.chunmi_eh3_e09c_cooker
        from: running
        to: idle
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.cooking_timer
    condition:
      - condition: time
        after: "08:00:00"
        before: "20:00:00"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.audible_notifications
                state: "on"
            sequence:
              - service: notify.alexa_media_bedroom_speaker
                data:
                  message: |
                    {{ [
                        "Dinner is served! Cooking is complete. Enjoy your meal!",
                        "Good news: Cooking is done! Your delicious meal is ready to be savored.",
                        "Chef's masterpiece: Cooking is complete. Your meal is now ready for enjoyment.",
                        "Cooking success: Your culinary creation is complete. Time to feast!",
                        "Ding! Cooking is finished. Your meal is hot and ready.",
                        "Culinary triumph: The cooking process is complete. Bon appétit!",
                        "Cooking achievement unlocked! Your meal is ready to be enjoyed."
                    ] | random }}
          - conditions:
              - condition: state
                entity_id: input_boolean.text_notifications
                state: "on"
            sequence:
              - service: script.text_notify
                data:
                  message: |
                    {{ [
                        "Dinner is served! Cooking is complete. Enjoy your meal!",
                        "Good news: Cooking is done! Your delicious meal is ready to be savored.",
                        "Chef's masterpiece: Cooking is complete. Your meal is now ready for enjoyment.",
                        "Cooking success: Your culinary creation is complete. Time to feast!",
                        "Ding! Cooking is finished. Your meal is hot and ready.",
                        "Culinary triumph: The cooking process is complete. Bon appétit!",
                        "Cooking achievement unlocked! Your meal is ready to be enjoyed."
                    ] | random }}
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.cooking_timer_finish

script:
  water_tank_low_notify:
    alias: Kitchen Water Tank Low Notification
    sequence:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: person.simplemice
                    state: home
                  - condition: state
                    entity_id: input_boolean.audible_notifications
                    state: "on"
            sequence:
              - repeat:
                  sequence:
                    - service: notify.alexa_media_bedroom_speaker
                      data:
                        message: |
                          {{ [
                              "Warning: Water tank level is low. Consider refilling it to ensure a continuous water supply.",
                              "Alert: The water tank is running low. Please check and refill to avoid interruptions.",
                              "Low water level detected! Ensure the water tank is replenished to avoid disruptions.",
                              "Attention: Water tank is nearly empty. Refill to maintain a sufficient water supply.",
                              "Urgent: Low water level in the tank. Take action to prevent any water shortages.",
                              "Water supply alert: The tank is low. Check and refill to avoid inconvenience.",
                              "Critical: Water tank level is low. Refill promptly to ensure a continuous water supply."
                            ] | random }}
                    - delay:
                        hours: 0
                        minutes: 10
                        seconds: 0
                        milliseconds: 0
                  until:
                    - type: is_value
                      condition: device
                      device_id: 9be7b2d13e72b6683f75158901d19ea5
                      entity_id: e46e9bc06cadd14b8a18f9eebe612743
                      domain: sensor
                      above: 30
          - conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.text_notifications
                    state: "on"
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: person.simplemice
                        state: not_home
                      - condition: state
                        entity_id: person.simplemice
                        state: Monkey Office
            sequence:
              - repeat:
                  sequence:
                    - service: script.text_notify
                      data:
                        message: |
                          {{ [
                              "Warning: Water tank level is low. Consider refilling it to ensure a continuous water supply.",
                              "Alert: The water tank is running low. Please check and refill to avoid interruptions.",
                              "Low water level detected! Ensure the water tank is replenished to avoid disruptions.",
                              "Attention: Water tank is nearly empty. Refill to maintain a sufficient water supply.",
                              "Urgent: Low water level in the tank. Take action to prevent any water shortages.",
                              "Water supply alert: The tank is low. Check and refill to avoid inconvenience.",
                              "Critical: Water tank level is low. Refill promptly to ensure a continuous water supply."
                            ] | random }}
                    - delay:
                        hours: 0
                        minutes: 45
                        seconds: 0
                        milliseconds: 0
                  until:
                    - type: is_value
                      condition: device
                      device_id: 9be7b2d13e72b6683f75158901d19ea5
                      entity_id: e46e9bc06cadd14b8a18f9eebe612743
                      domain: sensor
                      above: 30
    mode: restart
    icon: mdi:propane-tank-outline
