###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Kitchen
#   @description    :   Kitchen Automations.
###############################################################################

timer:
  cooking_timer:
    name: "Cooking Timer"
    duration: "01:00:00"
    icon: mdi:timer
    restore: true

input_boolean:
  cooking_mode:
    name: "Cooking Mode"
    icon: mdi:message-bulleted

input_datetime:
  cooking_timer_set:
    name: Cooking Timer Set
    has_date: false
    has_time: true

sensor:
  - platform: rest
    resource: "http://192.168.3.10:9925/api/groups/mealplans/today"
    method: GET
    name: Mealie todays meal
    headers:
      Authorization: !secret mealie
    value_template: "{{ value_json[0].recipe.name }}"
    force_update: true
    scan_interval: 30
  - platform: rest
    resource: "http://192.168.3.10:9925/api/groups/mealplans/today"
    method: GET
    name: Mealie todays meal ID
    headers:
      Authorization: !secret mealie
    value_template: "{{ value_json[0].recipe.id }}"
    force_update: true
    scan_interval: 30

automation:
  - id: test
    description: "Testing Cooking Timer"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - input_datetime.cooking_timer_set
    condition: []
    action:
      - service: timer.start
        data:
          duration: "{{ states('input_datetime.test_time') }}"
        target:
          entity_id: timer.cooking_timer

script:
  kitchen_water_tank_low_notification:
    alias: Kitchen Water Tank Low Notification
    sequence:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: person.simplemice
                    state: home
                  - condition: state
                    entity_id: input_boolean.audible_notifications
                    state: "on"
            sequence:
              - repeat:
                  sequence:
                    - service: script.speech_engine
                      data:
                        message: |
                          {{ [
                              "Warning: Water tank level is low. Consider refilling it to ensure a continuous water supply.",
                              "Alert: The water tank is running low. Please check and refill to avoid interruptions.",
                              "Low water level detected! Ensure the water tank is replenished to avoid disruptions.",
                              "Attention: Water tank is nearly empty. Refill to maintain a sufficient water supply.",
                              "Urgent: Low water level in the tank. Take action to prevent any water shortages.",
                              "Water supply alert: The tank is low. Check and refill to avoid inconvenience.",
                              "Critical: Water tank level is low. Refill promptly to ensure a continuous water supply."
                            ] | random }}
                    - delay:
                        hours: 0
                        minutes: 10
                        seconds: 0
                        milliseconds: 0
                  until:
                    - type: is_value
                      condition: device
                      device_id: 477f9b243ea2f15c2a3ab16cfac10fda
                      entity_id: a4096c28b097c8b66e950a85240f2d0c
                      domain: sensor
                      below: 10
          - conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.text_notifications
                    state: "on"
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: person.simplemice
                        state: not_home
                      - condition: state
                        entity_id: person.simplemice
                        state: Monkey Office
            sequence:
              - repeat:
                  sequence:
                    - service: script.text_notify
                      data:
                        message: |
                          {{ [
                              "Warning: Water tank level is low. Consider refilling it to ensure a continuous water supply.",
                              "Alert: The water tank is running low. Please check and refill to avoid interruptions.",
                              "Low water level detected! Ensure the water tank is replenished to avoid disruptions.",
                              "Attention: Water tank is nearly empty. Refill to maintain a sufficient water supply.",
                              "Urgent: Low water level in the tank. Take action to prevent any water shortages.",
                              "Water supply alert: The tank is low. Check and refill to avoid inconvenience.",
                              "Critical: Water tank level is low. Refill promptly to ensure a continuous water supply."
                            ] | random }}
                    - delay:
                        hours: 0
                        minutes: 30
                        seconds: 0
                        milliseconds: 0
                  until:
                    - type: is_value
                      condition: device
                      device_id: 477f9b243ea2f15c2a3ab16cfac10fda
                      entity_id: a4096c28b097c8b66e950a85240f2d0c
                      domain: sensor
                      above: 10
    mode: restart
    icon: mdi:propane-tank-outline
