###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Scripe
#   @description    :   Scripe automations.
###############################################################################

multiscrape:
  # Type Name
  - resource: https://www.motorist.co.th/en/petrol-prices
    scan_interval: 3600
    headers:
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
    sensor:
      - unique_id: gas_type_name
        name: Gas Name Type 95
        select: "body > main > div > div.container.pb-5.fuel_comparison > div:nth-child(1) > div > div > div > div.th-fuel-table > table > tbody > tr:nth-child(2) > td.text-left.th-grade-name"
        icon: mdi:gas-station
        #value_template: "{{ value and value or '' }}"

  - resource: https://www.motorist.co.th/en/petrol-prices
    scan_interval: 3600
    headers:
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
    sensor:
      - unique_id: gas_type_name1
        name: Gas Name Type 91
        select: "body > main > div > div.container.pb-5.fuel_comparison > div:nth-child(1) > div > div > div > div.th-fuel-table > table > tbody > tr:nth-child(5) > td.text-left.th-grade-name"
        icon: mdi:gas-station
        #value_template: "{{ value and value or '' }}"

  # Prices by Type
  - resource: https://www.motorist.co.th/en/petrol-prices
    scan_interval: 3600
    headers:
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
    sensor:
      - unique_id: gas_95_price_ptt
        name: Gasohol 95 (PTT)
        select: "body > main > div > div.container.pb-5.fuel_comparison > div:nth-child(1) > div > div > div > div.th-fuel-table > table > tbody > tr:nth-child(2) > td:nth-child(2)"
        icon: mdi:gas-station
        #value_template: "{{ value and value or '' }}"

  - resource: https://www.motorist.co.th/en/petrol-prices
    scan_interval: 3600
    headers:
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
    sensor:
      - unique_id: gas_91_price_ptt
        name: Gasohol 91 (PTT)
        select: "body > main > div > div.container.pb-5.fuel_comparison > div:nth-child(1) > div > div > div > div.th-fuel-table > table > tbody > tr:nth-child(5) > td:nth-child(2)"
        icon: mdi:gas-station
        #value_template: "{{ value and value or '' }}"

  - resource: https://www.motorist.co.th/en/petrol-prices
    scan_interval: 3600
    headers:
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
    sensor:
      - unique_id: gas_95_price_bcp
        name: Gasohol 95 (BCP)
        select: "body > main > div > div.container.pb-5.fuel_comparison > div:nth-child(1) > div > div > div > div.th-fuel-table > table > tbody > tr:nth-child(2) > td:nth-child(3)"
        icon: mdi:gas-station
        #value_template: "{{ value and value or '' }}"

  - resource: https://www.motorist.co.th/en/petrol-prices
    scan_interval: 3600
    headers:
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
    sensor:
      - unique_id: gas_91_price_bcp
        name: Gasohol 91 (BCP)
        select: "body > main > div > div.container.pb-5.fuel_comparison > div:nth-child(1) > div > div > div > div.th-fuel-table > table > tbody > tr:nth-child(5) > td:nth-child(3)"
        icon: mdi:gas-station
        #value_template: "{{ value and value or '' }}"

  - resource: https://www.motorist.co.th/en/petrol-prices
    scan_interval: 3600
    headers:
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
    sensor:
      - unique_id: gas_95_price_shell
        name: Gasohol 95 (Shell)
        select: "body > main > div > div.container.pb-5.fuel_comparison > div:nth-child(1) > div > div > div > div.th-fuel-table > table > tbody > tr:nth-child(2) > td:nth-child(4)"
        icon: mdi:gas-station
        #value_template: "{{ value and value or '' }}"

  - resource: https://www.motorist.co.th/en/petrol-prices
    scan_interval: 3600
    headers:
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
    sensor:
      - unique_id: gas_91_price_shell
        name: Gasohol 91 (Shell)
        select: "body > main > div > div.container.pb-5.fuel_comparison > div:nth-child(1) > div > div > div > div.th-fuel-table > table > tbody > tr:nth-child(5) > td:nth-child(4)"
        icon: mdi:gas-station
        #value_template: "{{ value and value or '' }}"
