###############################################################################
#   @author         :   Simplemice
#   @date           :   01/01/2024
#   @package        :   Phuket
#   @description    :   Just the Phuket Telegram
###############################################################################

automation:
  - id: holidays
    alias: Teleram Phuket Holidays
    description: ""
    trigger:
      - platform: calendar
        event: start
        offset: "8:30:0"
        entity_id: calendar.holidays_in_thailand
    condition: []
    action:
      - service: script.telegram_auto_holidays
        metadata: {}
        data: {}
    mode: single

  - id: weather
    alias: Telegram Phuket Weather
    description: ""
    trigger:
      - platform: time
        at: "09:55:00"
    condition: []
    action:
      - service: script.telegram_auto_weather
        metadata: {}
        data: {}
    mode: single

  - id: gasoline
    alias: Telegram Phuket Gasoline
    description: ""
    trigger:
      - platform: time
        at: "09:10:00"
    condition: []
    action:
      - service: script.telegram_gasoline
        data: {}
    mode: single

script:
  telegram_auto_moon:
    alias: "Telegram Phuket Full Moon"
    sequence:
      - service: script.telegram_phuket
        data:
          message: >-
            Moon Information at Phuket:
          image: >
            {{ [ "/config/www/tweet_images/moon.jpg",
                  "/config/www/tweet_images/moon1.jpg",
                  "/config/www/tweet_images/moon3.jpg",
                  "/config/www/tweet_images/moon2.jpg"] | random }}
          caption: >
            {{ [
              "Don't miss out on the moonlit magic. A full moon tonight! And no, we're not asking you to turn into a werewolf.",
              "Catch the Moon's best performance tonight: a 100% illuminated sky! Just make sure not to blame your lunacy on it.",
              "Tonight's forecast: 100% chance of a full moon. And zero percent chance of it being cheese... unfortunately.",
              "Full moon alert tonight! If you start howling, don't worry – we won't judge.",
              "Look out, the moon's in full glory tonight. Werewolves? We're not saying anything...just beware.",
              "Tonight, the moon is playing its leading role in the sky! Don't let the neighbor's bald head fool you, look up.",
              "Enjoy the full moon tonight! Just remember, staring too long might turn you into Picasso's next inspiration.",
              "The Moon's on full display tonight! Hopefully not as full as after your ice cream binge...",
              "Be sure not to mistake the neighbor's bright porch light for the full moon tonight.",
              "Full Moon party in the sky tonight! Just be sure, it's the moon and not a spotlight on your hidden stash of cookies.",
              "The moon is doing the whole 'being round and fully visible' thing tonight. Can't blame us if your belly is doing the same.",
              "Howling at the moon is scientifically proven to rid you of Monday blues. Don't knock it until you've tried it under tonight's full moon.",
              "High tide in the sky tonight with a full moon! And remember, it's not okay to blame the moon for high 'tide' in your laundry room.",
              "Remember to enjoy the full moon tonight, but don’t confuse it for a lunar eclipse when your neighbor's satellite dish gets in the way.",
              "Tonight's full moon is a sight to behold. But no, it's still not close enough to reach for a moon cheese sample.",
              "Tonight you can see the full lunar landing site from your backyard! Just don't expect any astronauts to wave back.",
              "A full moon tonight! But no, your phone battery won't die faster because of it.",
              "The moon has rounded up its act tonight! If your kid is bouncing off walls, can’t necessarily blame lunar gravity, can we?",
              "Catch the stunning full moon tonight! But don't fret, there's no alien invasion planned...as far as we know.",
              "Tonight's full moon: a perfect excuse to gaze skyward and ponder life's big questions. Like, why did they open a salad place next to a donut shop?"
            ] | random }}

              Moon Phase: {{ states('sensor.moon') }}

            #moon #fullmoon #phuket

  telegram_auto_holidays:
    alias: "Telegram Phuket Holidays"
    sequence:
      - service: script.telegram_phuket
        data_template:
          message: "Holidays Status"
          image: >
            {{ [ "/config/www/tweet_images/holiday.jpg",
                  "/config/www/tweet_images/holiday1.jpg",
                  "/config/www/tweet_images/holiday2.jpg",
                  "/config/www/tweet_images/holiday3.jpg"] | random }}
          caption: >
            {% set tasks = [state_attr('calendar.holidays_in_thailand', 'message')] | default([]) %}
            {% if tasks[0] != '' %}
              Today Holiday is:
              {% for task in tasks %}
                {{ task }}

                More information - https://en.wikipedia.org/wiki/{{task | replace(' ', '_')}}

              #thailand #phuket #holiday 
              {% endfor %}
            {% else %}
              Today No Holiday
            {% endif %}

  telegram_auto_birdnet:
    alias: "Telegram Phuket Birdnet"
    sequence:
      - service: script.telegram_phuket
        data_template:
          message: "BirdNet Status"
          image: >
            {{ [ "/config/www/tweet_images/bird.jpg",
                  "/config/www/tweet_images/bird1.jpg",
                  "/config/www/tweet_images/bird2.jpg",
                  "/config/www/tweet_images/bird3.jpg"] | random }}
          caption: >
            {% set bird_list = state_attr('sensor.birdnet_go_events','bird_events') | sort(attribute='time', reverse=true) | map(attribute='name') | unique | list %}
            {% set bird_objects = state_attr('sensor.birdnet_go_events','bird_events') | sort(attribute='time', reverse=true) %}
            Today Birds Detected Information:
              Total number of bird events: {{ bird_objects | length }}
              Total number of different birds detected: {{ bird_list | length }}
            Birds detected: 
              {% for bird_name in bird_list %} 
                {{bird_name}} https://en.wikipedia.org/wiki/{{bird_name | replace(' ', '_')}}
              {% endfor %}
            #birdnet #birds #autostatus #phuket

  telegram_auto_weather:
    alias: "Telegram Phuket Weather"
    sequence:
      - service: script.telegram_phuket
        data:
          message: >-
            Weather Information at Phuket:
          image: >
            {{ [ "/config/www/tweet_images/weather.jpg",
                  "/config/www/tweet_images/weather1.jpg",
                  "/config/www/tweet_images/weather2.jpg"] | random }}
          caption: >
            Weather Information at Phuket:
              Forecast Condition: {{ states('sensor.openweathermap_condition') }} / {{ states('sensor.openweathermap_forecast_condition') }}
              Temp & Hum: {{ states('sensor.openweathermap_forecast_temperature') }} °C / {{ states('sensor.openweathermap_humidity') }} %
              Pressure: {{ states('sensor.openweathermap_pressure') }} mmHg
              Precipitation: {{ state_translated('binary_sensor.rain_drop') }} - {{ states('sensor.pirateweather_precip_probability') }} % with {{ states('sensor.pirateweather_precip_intensity') }} mm/h
              AQI: {{ states('sensor.outside_aqi') }} µg/m³
              UV: {{ states('sensor.owm_ultraviolet_index') }} idx
              Ozone: {{ states('sensor.pirateweather_ozone') }} Du
              Wind speed: {{ states('sensor.pirateweather_wind_speed') }} m/s / {{ states('sensor.pirateweather_wind_bearing') }} °
              Visibility: {{ states('sensor.openweathermap_visibility') }} km
              Storm: {{ states('sensor.pirateweather_nearest_storm_distance') }} km / {{ states('sensor.pirateweather_nearest_storm_bearing') }} °
              Lighting Strike: {{ states('sensor.lighting_detector_lightning_counter') }} ↯ at {{ states('sensor.lighting_detector_lightning_distance') }} km distance
              Space Weather: M-Class flare {{ states('sensor.m_class_1_day_probability') }} % / X-Class flare {{ states('sensor.x_class_1_day_probability') }} % / Solar Flux {{ states('sensor.solar_flux_index') }}
            #weather #meteo #phuket

  telegram_gasoline:
    alias: "Telegram Phuket Gasoline"
    sequence:
      - service: script.telegram_phuket
        data:
          message: " The price of Gasohol 91 today {{ states('sensor.gas_91_price_ptt')}} THB and Gasohol 95 {{ states('sensor.gas_95_price_ptt')}} THB #phuket #gasoline #gasstation #ptt "
          image: >
            {{ [ "/config/www/tweet_images/gas_price.jpg",
                  "/config/www/tweet_images/gas_price1.jpg",
                  "/config/www/tweet_images/gas_price2.jpg"] | random }}
          caption: >
            {{ [
            "Today, Gasohol 91 is {{ states('sensor.lowest_91_gas_price')}} and Gasohol 95 is {{ states('sensor.lowest_95_gas_price')}} Remember, a journey of a thousand miles begins with a great gas price! #phuket #gasoline #gasstation",
            "Hurry up! Today's prices for Gasohol 91 is {{ states('sensor.lowest_91_gas_price')}} and Gasohol 95 is {{ states('sensor.lowest_95_gas_price')}} Who said laughter is the best fuel, clearly hasn't seen our prices! #phuket #gasoline #gasstation ",
            "Gasohol 91 is priced at {{ states('sensor.lowest_91_gas_price')}} and Gasohol 95 is {{ states('sensor.lowest_95_gas_price')}} today. Driving on empty? Fill up at PTT, where every liter counts, and so does every Baht. #phuket #gasoline #gasstation ",
            "Today, fill up your tank with Gasohol 91 at {{ states('sensor.lowest_91_gas_price')}} or Gasohol 95 at {{ states('sensor.lowest_95_gas_price')}} Because the only thing better than our jokes is our fuel prices. #phuket #gasoline #gasstation ",
            "Get Gasohol 91 for {{ states('sensor.lowest_91_gas_price')}} and Gasohol 95 for {{ states('sensor.lowest_95_gas_price')}} today. They say laughter is the best medicine, but with our fuel prices, you'll forget you were ever ailing! #phuket #gasoline #gasstation ",            
            "Hold on tight! The price of Gasohol 91 today is {{ states('sensor.lowest_91_gas_price')}} and Gasohol 95 is {{ states('sensor.lowest_95_gas_price')}} . That's more than your morning coffee! #phuket #gasoline #gasstation ",
            "The price of Gasohol 91 today {{ states('sensor.lowest_91_gas_price')}}  and Gasohol 95 {{ states('sensor.lowest_95_gas_price')}}  #phuket #gasoline #gasstation ",
            "The price of Gasohol 91 is {{ states('sensor.lowest_91_gas_price')}} and Gasohol 95 is {{ states('sensor.lowest_95_gas_price')}} today. Remember, it's not about the destination, but the journey and how much you saved on fuel at PTT! #phuket #gasoline #gasstation ",
            "Gasohol 91 is cruising at {{ states('sensor.lowest_91_gas_price')}} and Gasohol 95 is burning rubber at {{ states('sensor.lowest_95_gas_price')}} Get a full tank without emptying your wallet at PTT! #phuket #gasoline #gasstation ",
            "Gasohol 91 is priced at {{ states('sensor.lowest_91_gas_price')}} while Gasohol 95 is at {{ states('sensor.lowest_95_gas_price')}} With prices this low, your car's not the only thing that's going to be running! #phuket #gasoline #gasstation ",
            "Gasohol 91 for {{ states('sensor.lowest_91_gas_price')}} and Gasohol 95 for {{ states('sensor.lowest_95_gas_price')}} giving you more miles per gallon and more smiles per gallon! #phuket #gasoline #gasstation ",
            "Smile, at least for now. The price of Gasohol 91 today is {{ states('sensor.lowest_91_gas_price')}} and Gasohol 95 is {{ states('sensor.lowest_95_gas_price')}} . At least your wheels can't eat that much! #phuket #gasoline #gasstation ",
            "That is what I call climbing! Gasohol 91 today is {{ states('sensor.lowest_91_gas_price')}} and Gasohol 95 is {{ states('sensor.lowest_95_gas_price')}} . We'll all be riding bicycles at this rate. #phuket #gasoline #gasstation ",
            "If you think coffee is too expensive - take a look at our petrol prices! Gasohol 91 today is {{ states('sensor.lowest_91_gas_price')}} and Gasohol 95 is {{ states('sensor.lowest_95_gas_price')}} . So, you're still complaining about the cost of coffee? #phuket #gasoline #gasstation ",
            "Today, Gasohol 91 is at {{ states('sensor.gas91priceptt')}} THB and Gasohol 95 is at {{ states('sensor.gas95priceptt')}} THB. Don't drive on fumes - get your fuel at PTT - where the only gas we pass are savings! #phuket #gasoline #gasstation ",
            "Sure someone said petrol should be cheaper? Well, I've got news for you - Gasohol 91 today is {{ states('sensor.lowest_91_gas_price')}} and Gasohol 95 is {{ states('sensor.lowest_95_gas_price')}} . Looks like we all picked the wrong coin! #phuket #gasoline #gasstation "
            ] | random }}
