###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Presence
#   @description    :   A Collection of Presence Related Trackers and Sensors
###############################################################################
group:
  family:
    name: Family
    icon: mdi:human-female-female-child
    entities:
      - person.simplemice

input_datetime:
  mice_wakeup_alarm_time:
    name: WakeUp Alarm Time
    has_date: false
    has_time: true
  mice_work_alarm_time:
    name: Work Alarm Time
    has_date: false
    has_time: true
  mice_work_alarm_off:
    name: Work Alarm Off
    has_date: false
    has_time: true

input_select:
  here_destination_preset:
    name: Simplemice Destination
    options:
      - zone.home
      - zone.office
  house_room:
    name: Room Select
    options:
      - Garage
      - Livingroom
      - Bedroom
      - Kitchen
      - Bathroom
      - Backyard
    icon: mdi:hue:room-attic

input_boolean:
  presence_off:
    name: "Presence Mode Off"
    icon: mdi:location-enter
  guest_mode:
    name: "Guest Mode"
    icon: mdi:account-group
  vacation_mode:
    name: "Vacation Mode"
    icon: mdi:party-popper
  work_mode:
    name: "Work Mode"
    icon: mdi:briefcase

sensor:
  - platform: mqtt_room
    device_id: "iBeacon:a697d849-30ca-4bb0-8caa-ab489c4fd5c5-100-40004"
    unique_id: micemob_room
    name: "Micemob Room"
    state_topic: "espresense/devices/iBeacon:a697d849-30ca-4bb0-8caa-ab489c4fd5c5-100-40004"
    timeout: 5
    away_timeout: 30

  - platform: mqtt_room
    device_id: "name:l7_le"
    unique_id: micewatch_room
    name: "Micewatch Room"
    state_topic: "espresense/devices/name:l7_le"
    timeout: 5
    away_timeout: 30

  - platform: template
    sensors:
      family_home:
        friendly_name: "Family home"
        value_template: >
          {{ is_state('group.family', 'home') }}
        icon_template: >
          {% if is_state('sensor.family_home','0') %} mdi:account-off
          {% elif is_state('sensor.family_home','1') %} mdi:account
          {% elif is_state('sensor.family_home','2') %} mdi:account-multiple
          {% elif is_state('sensor.family_home','3') %} mdi:account-multiple-check
          {% else %} mdi:account-group
          {% endif %}

template:
  - sensor:
      - name: house_mode
        unique_id: house_mode
        state: >
          {% if is_state('input_boolean.sentry_mode','on') or is_state('input_boolean.barn_door_protocol','on')%}
            Secured
          {% elif is_state('input_boolean.guest_mode','on')%}
            Guest
          {% elif is_state('input_boolean.vacation_mode','on')%}
            Vacation
          {% elif is_state('binary_sensor.family_home','on') and (is_state('binary_sensor.quiet_time','on') or is_state('binary_sensor.overnight','on') )%}
            Sleep
          {% elif is_state('binary_sensor.family_home','on') and is_state('input_boolean.guest_mode','off')%}
            Normal
          {% elif is_state('binary_sensor.family_home','off') and is_state('input_boolean.baymax_mode','on')%}
            Monitoring
          {% else %}
            None
          {% endif %}
  - sensor:
      - name: "Wake Up Alarm"
        device_class: timestamp
        state: "{{ today_at(states('input_datetime.mice_wakeup_alarm_time')) }}"
  - sensor:
      - name: "Work Alarm"
        device_class: timestamp
        state: "{{ today_at(states('input_datetime.mice_work_alarm_time')) }}"

zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 50
    icon: mdi:home

automation:
  - id: 34c71e59-cd69-4481-c768-968807cf3537
    alias: Turn On Work Mode
    initial_state: true
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.mice_work_alarm_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.work_mode

  - id: 04018017-1cb8-45e0-c31d-b4005a48908d
    alias: Turn Off Work Mode
    initial_state: true
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (state_attr('input_datetime.mice_work_alarm_off', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.work_mode
        state: "on"
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.work_mode

  - id: 6d686767-7440-429a-b9e9-b12640663578
    alias: Update Micemob Room Presence
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.micemob_room
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
        enabled: true
    action:
      - service: device_tracker.see
        data:
          dev_id: micemob_track
          location_name: >
            {% if trigger.to_state.state in ['garage', 'livingroom', 'kitchen', 'bedroom',
            'bathroom', 'backyard'] %}
              home
            {% elif trigger.to_state.state == 'not_home' %}
              not_home
            {% else %}
              unknown
            {% endif %}

  - id: 6d686767-7440-429b-a2e4-a32640663578
    alias: Update Micewatch Room Presence
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.micewatch_room
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
        enabled: true
    action:
      - service: device_tracker.see
        data:
          dev_id: micewatch_track
          location_name: >
            {% if trigger.to_state.state in ['garage', 'livingroom', 'kitchen', 'bedroom',
            'bathroom', 'backyard'] %}
              home
            {% elif trigger.to_state.state == 'not_home' %}
              not_home
            {% else %}
              unknown
            {% endif %}

script:
