###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Security
#   @description    :   Everything related to security functions.
###############################################################################

group:
  house_security:
    name: "House Security"
    entities:
      - input_boolean.security_alarm
      - input_boolean.fire_alarm
      - input_boolean.leakage_alarm
      - input_boolean.safe_alarm
      - input_boolean.gas_alarm

input_boolean:
  sleep_door_checker:
    name: "Check Doors Before sleep"
    icon: mdi:door-closed-lock
  security_doors_open:
    name: "Security Doors Open"
    icon: mdi:door-closed-cancel
  security_alarm:
    name: Security Alarm
    icon: mdi:speaker-wireless
  fire_alarm:
    name: Fire Alarm
    icon: mdi:speaker-wireless
  gas_alarm:
    name: Gas Co2 Alarm
    icon: mdi:speaker-wireless
  leakage_alarm:
    name: Leakage Alarm
    icon: mdi:speaker-wireless
  safe_alarm:
    name: Safe Alarm
    icon: mdi:speaker-wireless

template:
  - binary_sensor:
      - name: Alarm Warnings
        state: >
          {{ is_state('binary_sensor.bathroom_water_leak', 'on')  
              or is_state('binary_sensor.kitchen_water_leak', 'on')
              or is_state('binary_sensor.gas_detector_gas', 'on')
              or is_state('binary_sensor.smoke_detector', 'on')
          }}
        device_class: safety
        icon: >
          {% if is_state("binary_sensor.alarm_warnings", "on") %}
          mdi:skull
          {% else %}
          mdi:shield-check
          {% endif %}

sensor:
  - platform: template
    sensors:
      bedroom_safe:
        friendly_name: "Bedroom Safe"
        value_template: >-
          {%- if is_state("alarm_control_panel.safe", "armed_home" ) %}
              Safe Armed
          {%- else -%}
              Safe Open
          {%- endif %}
        icon_template: >
          {% if is_state("alarm_control_panel.safe", "armed_home") %}
            mdi:safe
          {% else %}
            mdi:safe-square
          {% endif %}

binary_sensor:
  - platform: group
    name: "External Doors"
    device_class: opening
    entities:
      - binary_sensor.livingroom_door_contact
      - binary_sensor.backyard_door_contact

  - platform: group
    name: "Internal Doors"
    device_class: opening
    entities:
      - binary_sensor.bedroom_door_contact

automation:
  - id: ba39f2d2-8692-4cf4-a52c-529a1318bb14
    alias: Safe Alarm Automation
    description: ""
    trigger:
      - platform: tag
        tag_id: 609d3a2d-d4ce-4d27-8a07-b43d03d4583c
    condition:
      - condition: state
        entity_id: person.simplemice
        state: home
    action:
      - service: script.safe_security_automation
        metadata: {}
        data: {}
    mode: single

  - id: 39cdee89-4d72-4679-97a3-0e4c33fcec90
    alias: Doors Checked Before Sleep
    description: ""
    trigger:
      - platform: tag
        tag_id: ff348d89-fbf4-4f84-97d7-cde9413566ca
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: person.simplemice
            state: home
          - condition: state
            entity_id: input_boolean.sleep_door_checker
            state: "on"
    action:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.sleep_door_checker
      - service: script.speech_engine
        data:
          message: |
            {{ [
                'All doors secured. You may rest peacefully',
                'Doors checked and locked. Good night',
                'Safety check complete. All doors are locked',
                'Before bed routine executed. All doors are secured',
                'Ensuring safety before sleep. All doors have been checked and locked',
                'Sleep tight! All doors have been confirmed closed and locked',
                'Security sweep complete. All doors are now locked for the night'
            ] | random }}

  - id: c6ca90f9-87ff-489f-812e-a1ce448bc90f
    alias: Check All Doors Before Sleep
    description: ""
    trigger:
      - platform: state
        entity_id:
          - input_boolean.sleep_door_checker
        to: "on"
        from: "off"
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.audible_notifications
            state: "on"
    action:
      - repeat:
          sequence:
            - service: script.speech_engine
              data:
                message: |
                  {{ [
                      'Before you hit the sack, please ensure all doors are secure',
                      'Time to do a door check before bedtime. Safety first',
                      'Hey there! Do not forget to inspect all doors before going to sleep',
                      'Just a friendly reminder: it iss door-checking time before you catch some sleep time',
                      'Before you drift off, take a moment to make sure all doors are closed and locked',
                      'The nightly routine: checking all doors before you call it a night',
                      'Before you cozy up in bed, a quick door check is in order. Sweet dreams',
                      'To ensure a peaceful sleep, please verify that all doors are closed and locked',
                      'Last call for door checks! Let is make sure everything is secure before bedtime',
                      'Nedd Check Doors. I would close it for you. But I lack legs. And Arms',
                      'The automatic door closer appears to be broken. So, you know what to do. Time to get physical fo check doors',
                      'Before you say goodnight, double-check those doors. Safety is key'
                  ] | random }}
            - delay:
                hours: 0
                minutes: 2
                seconds: 0
                milliseconds: 0
          while:
            - condition: state
              entity_id: input_boolean.sleep_door_checker
              state: "on"

script:
  safe_security_automation:
    alias: Safe Security Automation
    sequence:
      - if:
          - condition: state
            entity_id: alarm_control_panel.safe
            state: armed_home
        then:
          - service: alarm_control_panel.alarm_disarm
            data:
              code: !secret alarm_code
            target:
              entity_id: alarm_control_panel.safe
          - service: script.speech_engine
            data:
              message: Safe Alarm Disarmed!
          - service: notify.alexa_media_portable_echo
            data:
              message: <audio src="soundbank://soundlibrary/alarms/car_alarms/car_alarm_05"/>
              data:
                type: tts
        else:
          - service: alarm_control_panel.alarm_arm_home
            data: {}
            target:
              entity_id: alarm_control_panel.safe
          - service: script.speech_engine
            data:
              message: Safe Alarm Armed!
          - service: notify.alexa_media_portable_echo
            data:
              message: <audio src="soundbank://soundlibrary/alarms/car_alarms/car_alarm_05"/>
              data:
                type: tts
    icon: mdi:safe
