###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Security
#   @description    :   Everything related to security functions.
###############################################################################

group:
  house_security:
    name: "House Security"
    entities:
      - input_boolean.security_alarm
      - input_boolean.fire_alarm
      - input_boolean.leakage_alarm
      - input_boolean.safe_alarm
      - input_boolean.gas_alarm

input_boolean:
  sleep_door_checker:
    name: "Check Doors Before sleep"
    icon: mdi:door-closed-lock
  security_doors_open:
    name: "Security Doors Open"
    icon: mdi:door-closed-cancel
  security_alarm:
    name: Security Alarm
    icon: mdi:speaker-wireless
  fire_alarm:
    name: Fire Alarm
    icon: mdi:speaker-wireless
  gas_alarm:
    name: Gas Co2 Alarm
    icon: mdi:speaker-wireless
  leakage_alarm:
    name: Leakage Alarm
    icon: mdi:speaker-wireless
  safe_alarm:
    name: Safe Alarm
    icon: mdi:speaker-wireless

template:
  - binary_sensor:
      - name: Alarm Warnings
        state: >
          {{ is_state('binary_sensor.bathroom_water_leak', 'on')  
              or is_state('binary_sensor.kitchen_water_leak', 'on')
              or is_state('binary_sensor.gas_detector_gas', 'on')
              or is_state('binary_sensor.smoke_detector', 'on')
          }}
        device_class: safety
        icon: >
          {% if is_state("binary_sensor.alarm_warnings", "on") %}
          mdi:skull
          {% else %}
          mdi:shield-check
          {% endif %}

sensor:
  - platform: template
    sensors:
      bedroom_safe:
        friendly_name: "Bedroom Safe"
        value_template: >-
          {%- if is_state("alarm_control_panel.safe", "armed_home" ) %}
              Safe Armed
          {%- else -%}
              Safe Open
          {%- endif %}
        icon_template: >
          {% if is_state("alarm_control_panel.safe", "armed_home") %}
            mdi:safe
          {% else %}
            mdi:safe-square
          {% endif %}

binary_sensor:
  - platform: group
    name: "Entrance Doors"
    device_class: opening
    entities:
      - binary_sensor.livingroom_door_contact
      - binary_sensor.backyard_door_contact

  - platform: group
    name: "Internal Doors"
    device_class: opening
    entities:
      - binary_sensor.bedroom_door_contact

automation:

script:
