###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Space Station
#   @description    :   A Collection of Notification Scripts and Configs.
###############################################################################

device_tracker:
  - platform: mqtt_json
    devices:
      iss: location/iss

sensor:
  - platform: rest
    scan_interval: 1800
    name: SpaceX
    json_attributes:
      - mission_name
      - launch_site
      - rocket
    value_template: '{{ value_json["launch_date_unix"] }}'
    resource: "https://api.spacexdata.com/v2/launches/next"

  #ISS Coordinates
  - platform: rest
    name: ISS Coordinates #Latitude & Longitude
    json_attributes:
      - iss_position
      - latitude
      - longitude
      - timestamp
    resource: "http://api.open-notify.org/iss-now.json"
    scan_interval:
      seconds: 30

  #ISS Rise Times
  - platform: rest
    name: ISS Pass times
    json_attributes:
      - request
      - response
    value_template: "{{ value_json.message }}"
    resource: "http://api.open-notify.org/iss-pass.json?lat=7.797183&lon=98.319593"
    scan_interval:
      seconds: 180

  - platform: rest
    name: ISS Crew
    json_attributes:
      - people
      - number
    value_template: "{{ value_json['number'] }}"
    resource: "http://api.open-notify.org/astros.json"

automation:
  - id: iss_location
    alias: "ISS Location Publish"
    trigger:
      - platform: state
        entity_id: sensor.iss_coordinates
    action:
      service: mqtt.publish
      data_template:
        topic: location/iss
        payload_template: '{"longitude": "{{ states.sensor.iss_coordinates.attributes.iss_position.longitude | float }}","latitude": "{{ states.sensor.iss_coordinates.attributes.iss_position.latitude | float }}"}'
        retain: true

  - id: iss_post
    initial_state: true
    alias: "Mastodon ISS Post"
    trigger:
      - platform: zone
        event: enter
        zone: zone.iss_overhead
        entity_id: device_tracker.iss
    action:
      - service: script.mastodon_notify_image
        data_template:
          message: >-
            {{ [
            "The #ISS is passing over. Wave. #Space #theycanseeourhouse ",
            "The #ISS just flew by with there are {{states.binary_sensor.iss.attributes.number_of_people_in_space}} people doing cool stuff. #Space #theycanseeourhouse",
            "The #ISS just flew by with {{states.binary_sensor.iss.attributes.number_of_people_in_space}} people in it. #Space #theycanseeourhouse"
            ] | random }}
          image: >-
            {{ [ "/config/www/tweet_images/iss.jpg",
                 "/config/www/tweet_images/iss3.jpg",
                 "/config/www/tweet_images/iss4.jpg",
                 "/config/www/tweet_images/iss2.jpg"] | random }}
      - service: script.twitter_notify_image
        data_template:
          tweet: >-
            {{ [
            "The #ISS is passing over. Wave. #Space #theycanseeourhouse ",
            "The #ISS just flew by with there are {{states.binary_sensor.iss.attributes.number_of_people_in_space}} people doing cool stuff. #Space #theycanseeourhouse",
            "The #ISS just flew by with {{states.binary_sensor.iss.attributes.number_of_people_in_space}} people in it. #Space #theycanseeourhouse"
            ] | random }}
          image: >-
            {{ [ "/config/www/tweet_images/iss.jpg",
                 "/config/www/tweet_images/iss3.jpg",
                 "/config/www/tweet_images/iss4.jpg",
                 "/config/www/tweet_images/iss2.jpg"] | random }}

  - id: full_moon
    initial_state: true
    alias: "Mastodon Full Moon Post"
    trigger:
      - platform: sun
        event: sunset
        offset: -00:15:00
    condition:
      - condition: state
        entity_id: sensor.moon
        state: "full_moon"
    action:
      - service: script.speech_engine
        data_template:
          who: "{{ states.sensor.alexa_audio.state }}"
          message: >
            <p>
              {{ [
              'There is a Full Moon out tonight. and this time it is the <emphasis>actual</emphasis> moon. And <emphasis>not</emphasis> the neighbor. ',
              'Hey look, There is the full moon. ',
              'The moon is <emphasis>huge<e/mphasis>! And full. ',
              'If you went outside right now you might see the full moon. <break time="2s"/> Of course if you wait long enough there will be one inside the house too. ',
              'If you want to see the full moon, <emphasis>tonight is the night</emphasis>.']
              | random }}
            </p>
      - service: script.twitter_notify_image
        data_template:
          tweet: >-
            {{ [
            "There is a Full Moon out tonight, and this time it's the actual moon and not the neighbor. ",
            "Hey look kids, There's the full moon. ",
            "The moon is huge! And full. "] | random + "#Space #fullmoon"}}
          image: >-
            {{ [ "/config/www/tweet_images/full_moon.jpg",
                "/config/www/tweet_images/moon2.jpeg",
                "/config/www/tweet_images/moon3.jpeg",
                "/config/www/tweet_images/moon4.jpeg",
                "/config/www/tweet_images/moon1.jpeg"
                ] | random }}
      - service: script.mastodon_notify_image
        data_template:
          tweet: >-
            {{ [
            "There is a Full Moon out tonight, and this time it's the actual moon and not the neighbor. ",
            "Hey look kids, There's the full moon. ",
            "The moon is huge! And full. "] | random + "#Space #fullmoon"}}
          image: >-
            {{ [ "/config/www/tweet_images/full_moon.jpg",
                "/config/www/tweet_images/moon2.jpeg",
                "/config/www/tweet_images/moon3.jpeg",
                "/config/www/tweet_images/moon4.jpeg",
                "/config/www/tweet_images/moon1.jpeg"
                ] | random }}
