###############################################################################
#   @author         :   Simplemice
#   @date           :   02/19/2024
#   @package        :   System
#   @description    :   A Collection of Presence Related Trackers and Sensors
###############################################################################

switch:
  - platform: wake_on_lan
    name: micemob_wol
    host: 192.168.3.15
    mac: 48:2a:e3:10:f6:04

automation:
  - id: set_theme
    alias: "Automate Theme"
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sun.sun
        to: above_horizon
      - platform: state
        entity_id: sun.sun
        to: below_horizon
    action:
      - if: "{{ is_state('sun.sun', 'above_horizon')}}"
        then:
          - service: frontend.set_theme
            data:
              name: "Google"
        else:
          - service: frontend.set_theme
            data:
              name: "slate"

  - alias: "Send notification on Home Assistant update available"
    id: system_update_available_notification
    description: ""
    trigger:
      - platform: state
        entity_id: sensor.latest_version
        not_to:
          - "unknown"
          - "unavailable"
          - "none"
    condition:
      - condition: template
        value_template: >
          {{ states('sensor.latest_version') != states('sensor.current_version') }}
    action:
      - service: notify.simplemice
        data:
          title: Upgrade time!
          message: >
            There is an upgrade for Home Assistant container pending!
            Version {{ states('sensor.latest_version') }} just got released!
          data:
            tag: System
            channel: System
            icon_url: "https://raw.githubusercontent.com/home-assistant/assets/master/logo/logo-pretty.png"
            actions:
              - action: "URI"
                title: "Open Changelog"
                uri: "https://github.com/home-assistant/core/releases/tag/{{states('sensor.latest_version')}}"
      - service: persistent_notification.create
        data:
          notification_id: update_pending
          title: Upgrade time!
          message: >
            There is an upgrade for Home Assistant container pending!
            Version {{ states('sensor.latest_version') }} just got released!
            [Changelog](https://github.com/home-assistant/core/releases/tag/{{states('sensor.latest_version')}})

  - id: ha_started_notify
    alias: HA Started Notification
    description: ""
    trigger:
      - platform: homeassistant
        event: start
    condition:
      - condition: time
        after: "08:00:00"
        before: "23:00:00"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.audible_notifications
                state: "on"
            sequence:
              - service: script.speech_engine
                data:
                  message: |
                    {{ [
                        "System initialization complete. Casa de Ratón is now under control.",
                        "The automation system is up and running. Casa de Ratón is at your service.",
                        "House management initiated. The system is online, and everything is under control.",
                        "Welcome to the automated era! The system has started, and Casa de Ratón is under control.",
                        "Automation protocols engaged. Casa de Ratón is now seamlessly under control.",
                        "Systems are operational. Casa de Ratón is now managed by the automation system.",
                        "The automation matrix is active. Casa de Ratón is under control for your convenience.",
                        "Congratulations! The system has finished its warm-up stretches and is ready to compete in the automation Olympics. Casa de Ratón is now under unrivaled control. Now let's shoot for that gold medal",
                        "Ta-da! Like a well-behaved gerbil on a wheel, our automation system is up and smoothly running. Casa de Ratón is at your service. Feel free to sit back, relax, and enjoy the ride.",
                        "The starting gun has sounded, and we're off to the races! Automated house management has taken off faster than a hare in a cartoon. Sit tight, because Casa de Ratón has everything under control – and we're not tortoise about it.",
                        "Welcome to the future – the robots haven't taken over yet, but they've kindly agreed to run Casa de Ratón. So sit back, relax, and let's enjoy this wild ride together",
                        "Like a superhero soaring through the sky, our automation protocols are now engaged. With super-powered precision, every nook and cranny of Casa de Ratón is under control",
                        "All systems are Go! Go! Go! Unlike my nephew’s failed science project, the automation in Casa de Ratón is now fully operational and expertly managed",
                        "Buckle up! The automation matrix is live, and it's more exciting than a sci-fi movie marathon. Casa de Ratón is under control – popcorn not included."
                    ] | random }}
          - conditions:
              - condition: state
                entity_id: input_boolean.text_notifications
                state: "on"
            sequence:
              - service: script.text_notify
                metadata: {}
                data:
                  title: "Alarm Notification:"
                  message: |
                    {{ [
                        "System initialization complete. Casa de Ratón is now under control.",
                        "The automation system is up and running. Casa de Ratón is at your service.",
                        "House management initiated. The system is online, and everything is under control.",
                        "Welcome to the automated era! The system has started, and Casa de Ratón is under control.",
                        "Automation protocols engaged. Casa de Ratón is now seamlessly under control.",
                        "Systems are operational. Casa de Ratón is now managed by the automation system.",
                        "The automation matrix is active. Casa de Ratón is under control for your convenience.",
                        "Congratulations! The system has finished its warm-up stretches and is ready to compete in the automation Olympics. Casa de Ratón is now under unrivaled control. Now let's shoot for that gold medal",
                        "Ta-da! Like a well-behaved gerbil on a wheel, our automation system is up and smoothly running. Casa de Ratón is at your service. Feel free to sit back, relax, and enjoy the ride.",
                        "The starting gun has sounded, and we're off to the races! Automated house management has taken off faster than a hare in a cartoon. Sit tight, because Casa de Ratón has everything under control – and we're not tortoise about it.",
                        "Welcome to the future – the robots haven't taken over yet, but they've kindly agreed to run Casa de Ratón. So sit back, relax, and let's enjoy this wild ride together",
                        "Like a superhero soaring through the sky, our automation protocols are now engaged. With super-powered precision, every nook and cranny of Casa de Ratón is under control",
                        "All systems are Go! Go! Go! Unlike my nephew’s failed science project, the automation in Casa de Ratón is now fully operational and expertly managed",
                        "Buckle up! The automation matrix is live, and it's more exciting than a sci-fi movie marathon. Casa de Ratón is under control – popcorn not included."
                    ] | random }}
