###############################################################################
#   @author         :   Simplemice
#   @date           :   01/01/2024
#   @package        :   Teleram
#   @description    :   Just the Telegram
###############################################################################

automation:

script:
  telegram_auto_news:
    alias: "Telegram Phuket News"
    sequence:
      - service: script.telegram_group_test
        data:
          message: >-
            About Information at Phuket:
              Thailand News: https://t.me/thailand_news
          image: >
            {{ [ "/config/www/tweet_images/news.jpg",
                  "/config/www/tweet_images/news1.jpg"] | random }}
          caption: >
            More Information about Phuket:
              Thailand News: https://t.me/thailand_news
            #about #ad #phuket

  telegram_rocket_launch:
    alias: "Telegram Rocket Lauch Messages"
    sequence:
      - service: script.telegram_group_test
        data:
          message: " "
          image: >
            {{ [ "/config/www/tweet_images/space.jpg",
                  "/config/www/tweet_images/space.jpg",
                  "/config/www/tweet_images/space.jpg"] | random }}
          caption: >
            Space Launch:
              Vehicle: {{ states['sensor.rocket_launch_1'].attributes["vehicle"] }} / Date: {{ states['sensor.rocket_launch_1'].attributes["launch_date_target"] }}
               Tags: {{ states['sensor.rocket_launch_1'].attributes["tags"] }}

              Vehicle: {{ states['sensor.rocket_launch_2'].attributes["vehicle"] }} / Date: {{ states['sensor.rocket_launch_2'].attributes["launch_date_target"] }}
               Tags: {{ states['sensor.rocket_launch_2'].attributes["tags"] }}

              Vehicle: {{ states['sensor.rocket_launch_3'].attributes["vehicle"] }} / Date: {{ states['sensor.rocket_launch_3'].attributes["launch_date_target"] }} 
               Tags: {{ states['sensor.rocket_launch_3'].attributes["tags"] }}

              Vehicle: {{ states['sensor.rocket_launch_4'].attributes["vehicle"] }} / Date: {{ states['sensor.rocket_launch_4'].attributes["launch_date_target"] }} 
               Tags: {{ states['sensor.rocket_launch_4'].attributes["tags"] }}

              Vehicle: {{ states['sensor.rocket_launch_5'].attributes["vehicle"] }} / Date: {{ states['sensor.rocket_launch_5'].attributes["launch_date_target"] }}
               Tags: {{ states['sensor.rocket_launch_5'].attributes["tags"] }}

            #space #launch #automation

  ##################
  ##################
  ##################
  ##################

  telegram_test:
    alias: "Telegram Test Messages"
    sequence:
      - service: script.telegram_group_test
        data:
          message: " "
          image: >
            {{ [ "/config/www/tweet_images/space.jpg",
                  "/config/www/tweet_images/space.jpg",
                  "/config/www/tweet_images/space.jpg"] | random }}
          caption: >
            Space Launch:
              Vehicle: {{ states['sensor.rocket_launch_1'].attributes["vehicle"] }} / Date: {{ states['sensor.rocket_launch_1'].attributes["launch_date_target"] }}
               Tags: {{ states['sensor.rocket_launch_1'].attributes["tags"] }}

              Vehicle: {{ states['sensor.rocket_launch_2'].attributes["vehicle"] }} / Date: {{ states['sensor.rocket_launch_2'].attributes["launch_date_target"] }}
               Tags: {{ states['sensor.rocket_launch_2'].attributes["tags"] }}

              Vehicle: {{ states['sensor.rocket_launch_3'].attributes["vehicle"] }} / Date: {{ states['sensor.rocket_launch_3'].attributes["launch_date_target"] }} 
               Tags: {{ states['sensor.rocket_launch_3'].attributes["tags"] }}

              Vehicle: {{ states['sensor.rocket_launch_4'].attributes["vehicle"] }} / Date: {{ states['sensor.rocket_launch_4'].attributes["launch_date_target"] }} 
               Tags: {{ states['sensor.rocket_launch_4'].attributes["tags"] }}

              Vehicle: {{ states['sensor.rocket_launch_5'].attributes["vehicle"] }} / Date: {{ states['sensor.rocket_launch_5'].attributes["launch_date_target"] }}
               Tags: {{ states['sensor.rocket_launch_5'].attributes["tags"] }}

            #space #launch #automation
