###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Weather
#   @description    :   Weather automations.
###############################################################################
group:
  weather_alerts:
    name: "Weather Alerts Group"
    entities:
      - input_boolean.lighting_alert
      - input_boolean.rain_alert
      - input_boolean.weather_alert

input_boolean:
  weather_alert:
    name: "Weather Alert Notification"
    icon: mdi:weather-lightning-rainy
  rain_alert:
    name: "Rain Alert Notification"
    icon: mdi:weather-pouring
  lighting_alert:
    name: "Lighting Alert Notification"
    icon: mdi:flash-alert

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: "past_day_all_earthquakes"
    radius: 2000
    minimum_magnitude: 0.0

utility_meter:
  rain_daily:
    source: sensor.pirateweather_precip_intensity
    name: Rain Daily
    cycle: daily
    delta_values: true
  rain_monthly:
    source: sensor.pirateweather_precip_intensity
    name: Rain Monthly
    cycle: monthly
    delta_values: true
  rain_yearly:
    source: sensor.pirateweather_precip_intensity
    name: Rain Yearly
    cycle: yearly
    delta_values: true

sensor:
  - platform: history_stats
    name: Dayly Rain Duration
    entity_id: sensor.rain_drop
    state: "on"
    type: count
    end: "{{ now().replace(hour=9, minute=0, second=0) }}"
    duration:
      hours: 730

  - platform: template
    sensors:
      rain_sensor:
        friendly_name: "Rain Sensor"
        value_template: >-
          {%- if is_state("binary_sensor.rain_drop", "off" ) %}
              No Rain
          {%- else -%}
              Rain Now
          {%- endif %}
        icon_template: >
          {% if is_state("binary_sensor.rain_drop", "off") %}
            mdi:weather-sunny
          {% else %}
            mdi:weather-pouring
          {% endif %}

  - platform: group
    name: "Outside Temp"
    unique_id: outside_temp
    type: mean
    entities:
      - sensor.porch_temp_temperature
      - sensor.backyard_temp_temperature

  - platform: group
    name: "Outside Humidity"
    unique_id: outside_hum
    type: mean
    entities:
      - sensor.porch_temp_humidity
      - sensor.backyard_temp_humidity

  - platform: group
    name: "Outside AQI"
    unique_id: outside_aqi
    type: mean
    entities:
      - sensor.air_quality_index
      - sensor.u_s_air_quality_index

  - platform: openweathermap_all
    api_key: !secret openweather_all
    latitude: !secret weather_lat
    longitude: !secret weather_long

automation:
  - id: 3059db4c-8602-4ab6-8cf4-1d07c5992d86
    alias: Rain Outside Notification
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.rain_drop
        to: "on"
    condition:
      - condition: time
        after: "08:00:00"
        before: "20:00:00"
      - condition: state
        entity_id: input_boolean.weather_alert
        state: "on"
    action:
      - service: script.rain_outside_notification
        metadata: {}
        data: {}

script:
  rain_outside_notification:
    alias: Rain Outside Notification
    sequence:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.audible_notifications
                    state: "on"
                  - condition: state
                    entity_id: input_boolean.weather_alert
                    state: "on"
            sequence:
              - service: script.speech_engine
                data:
                  message: |
                    {{ [
                        "Rain alert: It's currently raining outside. Take necessary precautions when heading outdoors.",
                        "Attention: Rain detected outside. Don't forget your umbrella if you plan to go out.",
                        "Rainy weather: It's currently raining. Consider adjusting your plans accordingly.",
                        "Weather update: Rain is falling outside. Stay dry and be cautious on the roads.",
                        "Umbrella time: Rain detected outside. Grab an umbrella before heading out.",
                        "Rainfall alert: It's raining. Make sure to check the weather conditions before going outside.",
                        "Rainy day reminder: The weather outside is rainy. Take appropriate measures for your activities."
                    ] | random }}
              - service: select.select_option
                target:
                  entity_id: select.wled_matrix_preset
                data:
                  option: Lightning
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 10
                  milliseconds: 0
              - service: notify.alexa_media_portable_echo
                data:
                  message: >-
                    <audio
                    src="soundbank://soundlibrary/weather/thunder/thunder_10"/>
                  data:
                    type: tts
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 5
                  milliseconds: 0
              - service: notify.alexa_media_portable_echo
                data:
                  message: >-
                    <audio
                    src="soundbank://soundlibrary/weather/thunder/thunder_10"/>
                  data:
                    type: tts
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 5
                  milliseconds: 0
              - service: select.select_option
                data:
                  option: Black Hole
                target:
                  entity_id: select.wled_matrix_preset
          - conditions:
              - condition: state
                entity_id: input_boolean.text_notifications
                state: "on"
            sequence:
              - service: notify.simplemice
                data:
                  message: TTS
                  data:
                    media_stream: alarm_stream_max
                    tts_text: |
                      {{ [
                          "Rain alert: It's currently raining outside. Take necessary precautions when heading outdoors.",
                          "Attention: Rain detected outside. Don't forget your umbrella if you plan to go out.",
                          "Rainy weather: It's currently raining. Consider adjusting your plans accordingly.",
                          "Weather update: Rain is falling outside. Stay dry and be cautious on the roads.",
                          "Umbrella time: Rain detected outside. Grab an umbrella before heading out.",
                          "Rainfall alert: It's raining. Make sure to check the weather conditions before going outside.",
                          "Rainy day reminder: The weather outside is rainy. Take appropriate measures for your activities."
                      ] | random }}
              - service: script.text_notify
                data:
                  message: |
                    {{ [
                        "Rain alert: It's currently raining outside. Take necessary precautions when heading outdoors.",
                        "Attention: Rain detected outside. Don't forget your umbrella if you plan to go out.",
                        "Rainy weather: It's currently raining. Consider adjusting your plans accordingly.",
                        "Weather update: Rain is falling outside. Stay dry and be cautious on the roads.",
                        "Umbrella time: Rain detected outside. Grab an umbrella before heading out.",
                        "Rainfall alert: It's raining. Make sure to check the weather conditions before going outside.",
                        "Rainy day reminder: The weather outside is rainy. Take appropriate measures for your activities."
                    ] | random }}
              - service: script.telegram_auto_rain
    icon: fas:cloud-rain
