language: en
intents:
  HassTurnOff:
    data:
      - sentences:
          - "<close> <name> [in <area>]"
        requires_context:
          domain: cover
        response: cover

      - sentences:
          - "<close> [the] garage door"
        slots:
          domain: cover
          device_class: garage
        response: cover_device_class

      - sentences:
          - "<close> [the] {cover_classes:device_class} in <area>"
          - "<close> <area> {cover_classes:device_class}"
        slots:
          domain: cover
        response: cover_device_class

      - sentences:
          - "<close> [the] {cover_classes:device_class}[<in_here>]"
        expansion_rules:
          in_here: "[ in] here"
        slots:
          domain: cover
        response: cover_device_class
        requires_context:
          area:
            slot: true
