language: en
intents:
  HassSetPosition:
    data:
      - sentences:
          - "(<numeric_value_set>|<open>|<close>) <name> [position ]to <position>"
        requires_context:
          domain: cover
        slots:
          domain: cover

      - sentences:
          - "(<numeric_value_set>|<open>|<close>) [the ]{cover_classes:device_class}[ position] (to <position>;in <area>)"
          - "(<numeric_value_set>|<open>|<close>) <area> {cover_classes:device_class}[ position] to <position>"
        slots:
          domain: cover
