language: "en"
intents:
  HassTurnOn:
    data:
      - sentences:
          - "<turn> on [all] [the] fan[s] in <area>"
          - "<turn> on <area> fan[s]"
          - "[<turn>] [all] <area> fan[s] on"
          - "activate [all] <area> fan[s]"
          - "activate [all] fan[s] [in] <area>"
        slots:
          domain: "fan"
          name: "all"
        response: fans_area

      - sentences:
          - "<turn> on[ all][ the] fan[s][<in_here>]"
          - "<turn>[ all][ the] fan[s]( on;<in_here>)"
          - "<turn>[ all][ the] fan[s] on"
        response: "fans_area"
        expansion_rules:
          in_here: "[ in] here"
        slots:
          domain: fan
        requires_context:
          area:
            slot: true
