language: "en"
intents:
  HassTurnOff:
    data:
      - sentences:
          - "<turn> off [all] [the] fan[s] in <area>"
          - "<turn> off <area> fan[s]"
          - "[<turn>] [all] <area> fan[s] off"
          - "[<turn>] [all] [the] fan[s] [in] <area> off"
          - "deactivate [all] [the] fan[s] [in] <area>"
          - "deactivate [all] <area> [the] fan[s]"
        slots:
          domain: "fan"
          name: "all"
        response: fans_area

      - sentences:
          - "[<turn>] (all [the] fan[s] off|[the] fan[s] off everywhere)"
          - "deactivate (all [the] fan[s]|[the] fan[s] everywhere)"
        response: "light_all"
        slots:
          domain: "fan"
          name: "all"

      - sentences:
          - "<turn> off[ all][ the] fan[s][<in_here>]"
          - "<turn>[ all][ the] fan[s]( off;<in_here>)"
          - "<turn>[ all][ the] fan[s] off"
        response: "fans_area"
        expansion_rules:
          in_here: "[ in] here"
        slots:
          domain: fan
        requires_context:
          area:
            slot: true
