language: en
intents:
  HassTurnOff:
    data:
      - sentences:
          - "<turn> off (<area> <name>|<name> [in <area>])"
          - "[<turn>] (<area> <name>|<name> [in <area>]) [to] off"
          - "deactivate (<area> <name>|<name> [in <area>])"
        excludes_context:
          domain:
            - binary_sensor
            - cover
            - lock
            - scene
            - script
            - sensor
