language: "en"
intents:
  HassLightSet:
    data:
      # brightness
      - sentences:
          - "[<numeric_value_set>] <name> brightness [to] <brightness>"
          - "[<numeric_value_set>] [the] brightness [of] <name> [to] <brightness>"
          - "[<numeric_value_set>] <name> [to] <brightness> [brightness]"
        response: "brightness"
        requires_context:
          domain: light

      - sentences:
          - "<numeric_value_set> <name> to <brightness>"
        requires_context:
          domain: "light"
        response: "brightness"
      - sentences:
          - "[<numeric_value_set>] [the] brightness in <area> to <brightness>"
          - "[<numeric_value_set>] [the] brightness of <area> to <brightness>"
          - "[<numeric_value_set>] <area> brightness [to] <brightness>"
          - "[<numeric_value_set>] <area> [to] <brightness> brightness"
          - "[<numeric_value_set>] <area> [to] <brightness>"
          - "[<numeric_value_set>] [all] [the] lights [<in>] <area> to <brightness> [brightness]"
        slots:
          name: "all"
        response: "brightness"

      - sentences:
          - "<numeric_value_set> <area> to <brightness>"
        slots:
          name: "all"
        response: "brightness"

      - sentences:
          - "[<numeric_value_set>] [the] brightness to <brightness>"
          - "[<numeric_value_set>] [the] brightness (<in_here>;to <brightness>)"
        expansion_rules:
          in_here: "[ in] here"
        response: "brightness"
        requires_context:
          area:
            slot: true

      # Max/Min brightness
      - sentences:
          - "[<numeric_value_set>] <name> brightness to [the] {brightness_level:brightness}"
          - "[<numeric_value_set>] [the] brightness of <name> to [the] {brightness_level:brightness}"
          - "[<numeric_value_set>] <name> [to] [the] {brightness_level:brightness} brightness"
        requires_context:
          domain: light
        response: "brightness"

      - sentences:
          - "[<numeric_value_set>] [the] brightness in <area> to [the] {brightness_level:brightness}"
          - "[<numeric_value_set>] [the] brightness of <area> to [the] {brightness_level:brightness}"
          - "[<numeric_value_set>] <area> brightness to [the] {brightness_level:brightness}"
          - "[<numeric_value_set>] <area> [to] [the] {brightness_level:brightness} brightness"
        slots:
          name: "all"
        response: "brightness"

      - sentences:
          - "[<numeric_value_set>] [the] brightness to [the] {brightness_level:brightness}"
          - "[<numeric_value_set>] [the] brightness (<in_here>;to [the] {brightness_level:brightness})"
        expansion_rules:
          in_here: "[ in] here"
        response: "brightness"
        requires_context:
          area:
            slot: true

      # color
      - sentences:
          - "[<set>] <name> [color] [to] {color}"
          - "[<set>] [[the] color of] <name> to {color}"
        requires_context:
          domain: light
        response: "color"
      - sentences:
          - "[<set>] [[the] color of] (<area> | [all [the]] lights in <area> | [all] <area> lights) [to] {color}"
          - "[<set>] (<area> | [all] lights in <area> | [all] <area> lights) [color] [to] {color}"
        slots:
          name: "all"
        response: "color"

      - sentences:
          - "[<set>] [[the] color of] [all] <light> [to] {color}"
          - "[<set>] [[the] color of] [all] <light> (<in_here>;[to] {color})"
        expansion_rules:
          in_here: "[ in] here"
        response: "color"
        requires_context:
          area:
            slot: true
