language: "en"
intents:
  HassTurnOff:
    data:
      - sentences:
          - "<turn> off (<area> <name> <light_devices>|<name> <light_devices> [in <area>])"
          - "[<turn>] (<area> <name> <light_devices>|<name> <light_devices> [in <area>]) [to] off"
          - "deactivate (<area> <name> <light_devices>|<name> <light_devices> [in <area>])"
        expansion_rules:
          light_devices: "(light[s]|[light] switch[es])"
        requires_context:
          domain: "light"
      - sentences:
          - "<turn> off [all] <light> in <area>"
          - "<turn> off [all] <area> <light>"
          - "[<turn>] [all] <area> <light> off"
          - "[<turn>] [all] <light> [in] <area> off"
          - "deactivate [all] <light> [in] <area>"
          - "deactivate [all] <area> <light>"
        slots:
          domain: "light"
        response: "lights_area"

      - sentences:
          - "[<turn>] (all <light> off|<light> off everywhere)"
          - "deactivate (all <light>|<light> everywhere)"
        response: "light_all"
        slots:
          domain: "light"
          name: "all"

      # Turn off lights in the same area as a satellite device
      - sentences:
          - "<turn> off[ all] <light>[<in_here>]"
          - "<turn>[ all] <light>( off;<in_here>)"
          - "<turn>[ all] <light> off"
        response: "lights_area"
        expansion_rules:
          in_here: "[ in] here"
        slots:
          domain: "light"
        requires_context:
          area:
            slot: true
