language: en
intents:
  HassTurnOff:
    data:
      - sentences:
          - "unlock <name> [in <area>]"
        requires_context:
          domain: lock
        response: lock

      - sentences:
          - "unlock [all] [the] [(lock|door)[s]] [in] <area>"
          - "unlock [all] <area> [(lock|door)[s]]"
        slots:
          domain: "lock"
          name: "all"
        response: lock
