language: en
intents:
  HassTurnOn:
    data:
      - sentences:
          - "lock <name> [in <area>]"
        requires_context:
          domain: lock
        response: lock

      - sentences:
          - "lock [all] [the] [(lock|door)[s]] [in] <area>"
          - "lock [all] <area> [(lock|door)[s]]"
        slots:
          domain: "lock"
          name: "all"
        response: lock
