language: en
intents:
  HassSetVolume:
    data:
      - sentences:
          - "<numeric_value_set> <name> volume to <volume> [percent]"
          - "turn <name> [volume] (up|down) to <volume> [percent]"
          - "(<numeric_value_set> the volume to <volume> [percent];[on ]<name>)"
          - "(turn (the volume;(up|down)) to <volume> [percent];[on ]<name>)"
        requires_context:
          domain: media_player
