language: en
intents:
  HassMediaNext:
    data:
      - sentences:
          - "next [track|item] [on|for] <name>"
          - "(skip [(to [the ]next [(song|track)]|([the ](song|track)|this [(song|track)]) )];[on ]<name>)"
        requires_context:
          domain: media_player
