language: en
intents:
  HassGetState:
    data:
      # https://www.home-assistant.io/integrations/person/
      - sentences:
          - "<where_is> <name>"
        response: where
        requires_context:
          domain: person
        slots:
          domain: person

      - sentences:
          - "is <name> [<in>] [the] {zone:state}"
        response: one_yesno
        requires_context:
          domain: person
        slots:
          domain: person

      - sentences:
          - "is anyone [<in>] [the] {zone:state}"
        response: any
        slots:
          domain: person

      - sentences:
          - "is everyone [<in>] [the] {zone:state}"
        response: all
        slots:
          domain: person

      - sentences:
          - "who is [<in>] [the] {zone:state}"
        response: which
        slots:
          domain: person

      - sentences:
          - "how many people are [<in>] [the] {zone:state}"
        response: how_many
        slots:
          domain: person
