language: en
intents:
  HassTurnOn:
    data:
      - sentences:
          - "[run|start|<turn>] <name> [script] [on]"
        requires_context:
          domain: script
        slots:
          domain: script
        response: script
