language: en
intents:
  HassGetState:
    data:
      # https://www.home-assistant.io/integrations/sensor/
      # Apparent power
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: apparent_power
        slots:
          domain: sensor
          device_class: apparent_power
        expansion_rules:
          class: "apparent power"

      # AQI
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: aqi
        slots:
          domain: sensor
          device_class: aqi
        expansion_rules:
          class: "(AQI|air quality [index])"

      # Atmospheric pressure
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: atmospheric_pressure
        slots:
          domain: sensor
          device_class: atmospheric_pressure
        expansion_rules:
          class: "(atmospheric|air) pressure"

      # Battery
      - sentences:
          - "<what_is_the_class_of_name>"
          - "how much battery (does <name> have [left]|has <name> got [left]|is left in <name>)"
        response: one
        requires_context:
          domain: sensor
          device_class: battery
        slots:
          domain: sensor
          device_class: battery
        expansion_rules:
          class: "[remaining] battery [level]"

      # CO2
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: carbon_dioxide
        slots:
          domain: sensor
          device_class: carbon_dioxide
        expansion_rules:
          class: "(carbon dioxide|CO2) (level|concentration)"

      # CO
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: carbon_monoxide
        slots:
          domain: sensor
          device_class: carbon_monoxide
        expansion_rules:
          class: "(carbon monoxide|CO) (level|concentration)"

      # Current
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: current
        slots:
          domain: sensor
          device_class: current
        expansion_rules:
          class: "[amount of] [electric[al]] current"

      # Data rate
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: data_rate
        slots:
          domain: sensor
          device_class: data_rate
        expansion_rules:
          class: "[(download|upload|data)] (rate|speed)"

      # Data size
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: data_size
        slots:
          domain: sensor
          device_class: data_size
        expansion_rules:
          class: "([data] size|(amount|size) of [the] data)"

      # Date
      - sentences:
          - "<what_is_the_class_of_name>"
          - "when ((is|was) <name>|will <name> be|(will|did) <name> happen)"
        response: one
        requires_context:
          domain: sensor
          device_class: date
        slots:
          domain: sensor
          device_class: date
        expansion_rules:
          class: "[calendar[istic]] date"

      # Distance
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: distance
        slots:
          domain: sensor
          device_class: distance
        expansion_rules:
          class: "distance"

      # Duration
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: duration
        slots:
          domain: sensor
          device_class: duration
        expansion_rules:
          class: "duration"

      # Energy
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: energy
        slots:
          domain: sensor
          device_class: energy
        expansion_rules:
          class: "[amount of] energy"

      # Energy storage
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: energy_storage
        slots:
          domain: sensor
          device_class: energy_storage
        expansion_rules:
          class: "[[total] amount of] [stored] energy"

      # Skipping enum

      # Frequency
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: frequency
        slots:
          domain: sensor
          device_class: frequency
        expansion_rules:
          class: "frequency"

      # Gas
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: gas
        slots:
          domain: sensor
          device_class: gas
        expansion_rules:
          class: "[amount of] gas [volume]"

      # Humidity
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: humidity
        slots:
          domain: sensor
          device_class: humidity
        expansion_rules:
          class: "[(air|atmospheric)] [relative] humidity"

      # Illuminance
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: illuminance
        slots:
          domain: sensor
          device_class: illuminance
        expansion_rules:
          class: "([amount of] illuminance|(light|brightness) level)"

      # Irradiance
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: irradiance
        slots:
          domain: sensor
          device_class: irradiance
        expansion_rules:
          class: "([amount of] irradiance|[ir]radiation level)"

      # Moisture
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: moisture
        slots:
          domain: sensor
          device_class: moisture
        expansion_rules:
          class: "([relative] moisture|(percentage|ratio) of water)"

      # Monetary
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: monetary
        slots:
          domain: sensor
          device_class: monetary
        expansion_rules:
          class: "[amount of] (money|cash|cost)"

      # Nitrogen dioxide
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: nitrogen_dioxide
        slots:
          domain: sensor
          device_class: nitrogen_dioxide
        expansion_rules:
          class: "(nitrogen dioxide|NO2) (level|concentration)"

      # Nitrogen monoxide
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: nitrogen_monoxide
        slots:
          domain: sensor
          device_class: nitrogen_monoxide
        expansion_rules:
          class: "(nitrogen monoxide|NO) (level|concentration)"

      # Nitrous oxide
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: nitrous_oxide
        slots:
          domain: sensor
          device_class: nitrous_oxide
        expansion_rules:
          class: "(nitrous oxide|N2O) (level|concentration)"

      # Ozone
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: ozone
        slots:
          domain: sensor
          device_class: ozone
        expansion_rules:
          class: "(ozone|O3) level"

      # PM1
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: pm1
        slots:
          domain: sensor
          device_class: pm1
        expansion_rules:
          class: "((level|concentration) [of] PM1 [particles]|PM1 [particles] [level|concentration])"

      # PM2.5
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: pm25
        slots:
          domain: sensor
          device_class: pm25
        expansion_rules:
          class: "((level|concentration) [of] PM2.5 [particles]|PM2.5 [particles] [level|concentration])"

      # PM10
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: pm10
        slots:
          domain: sensor
          device_class: pm10
        expansion_rules:
          class: "((level|concentration) [of] PM10 [particles]|PM10 [particles] [level|concentration])"

      # Power factor
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: power_factor
        slots:
          domain: sensor
          device_class: power_factor
        expansion_rules:
          class: "power factor"

      # Power
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: power
        slots:
          domain: sensor
          device_class: power
        expansion_rules:
          class: "power"

      # Precipitation
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: precipitation
        slots:
          domain: sensor
          device_class: precipitation
        expansion_rules:
          class: "[accumulated] (precipitation|(rain|snow)[fall]) [level|quantity]"

      # Precipitation intensity
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: precipitation_intensity
        slots:
          domain: sensor
          device_class: precipitation_intensity
        expansion_rules:
          class: "(precipitation|(rain|snow)[fall]) (intensity|rate)"

      # Pressure
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: pressure
        slots:
          domain: sensor
          device_class: pressure
        expansion_rules:
          class: "pressure"

      # Reactive power
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: reactive_power
        slots:
          domain: sensor
          device_class: reactive_power
        expansion_rules:
          class: "reactive power"

      # Signal strength
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: signal_strength
        slots:
          domain: sensor
          device_class: signal_strength
        expansion_rules:
          class: "signal strength"

      # Sound pressure
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: sound_pressure
        slots:
          domain: sensor
          device_class: sound_pressure
        expansion_rules:
          class: "(sound|acoustic) pressure"

      # Speed
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: speed
        slots:
          domain: sensor
          device_class: speed
        expansion_rules:
          class: "(speed|velocity)"

      # Sulphur dioxide
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: sulphur_dioxide
        slots:
          domain: sensor
          device_class: sulphur_dioxide
        expansion_rules:
          class: "(sulphur dioxide|SO2) (level|concentration)"

      # Temperature
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: temperature
        slots:
          domain: sensor
          device_class: temperature
        expansion_rules:
          class: "temperature"

      # Skipping Timestamp

      # Volatile organic compounds
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: volatile_organic_compounds
        slots:
          domain: sensor
          device_class: volatile_organic_compounds
        expansion_rules:
          class: "[concentration of] (VOC[s]|[volatile] organic compound[s])"

      # Volatile organic compounds
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: volatile_organic_compounds_parts
        slots:
          domain: sensor
          device_class: volatile_organic_compounds_parts
        expansion_rules:
          class: "[(concentration|ratio) of] (VOC[s]|[volatile] organic compound[s])"

      # Voltage
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: voltage
        slots:
          domain: sensor
          device_class: voltage
        expansion_rules:
          class: "voltage [drop]"

      # Volume
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: volume
        slots:
          domain: sensor
          device_class: volume
        expansion_rules:
          class: "volume"

      # Volume storage
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: volume_storage
        slots:
          domain: sensor
          device_class: volume_storage
        expansion_rules:
          class: "[total] [stored] volume"

      # Water
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: water
        slots:
          domain: sensor
          device_class: water
        expansion_rules:
          class: "[total] ([amount of] [consumed] water|water consumption)"

      # Weight
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: weight
        slots:
          domain: sensor
          device_class: weight
        expansion_rules:
          class: "(weight|mass)"

      # Wind speed
      - sentences:
          - "<what_is_the_class_of_name>"
        response: one
        requires_context:
          domain: sensor
          device_class: wind_speed
        slots:
          domain: sensor
          device_class: wind_speed
        expansion_rules:
          class: "[wind] (speed|velocity)"
