language: "en"
intents:
  HassShoppingListAddItem:
    data:
      - sentences:
          - add <item> to<my_list>
          - put <item> (on|in)<my_list>
        response: item_added
        expansion_rules:
          my_list: "[ my| the][ shopping] list"
          item: "{shopping_list_item:item}"
