language: en
intents:
  HassSetPosition:
    data:
      - sentences:
          - "(<numeric_value_set>|<open>|<close>) <name> [position ]to <position>"
        requires_context:
          domain: valve
        slots:
          domain: valve
