language: en
intents:
  HassTurnOff:
    data:
      - sentences:
          - "<close> <name>"
        requires_context:
          domain: valve
        slots:
          domain: valve
        response: valve
