language: en
intents:
  HassTurnOn:
    data:
      - sentences:
          - "<open> <name>"
        requires_context:
          domain: valve
        slots:
          domain: valve
        response: valve
