language: en
intents:
  HassGetWeather:
    data:
      - sentences:
          - "<what_is>[ the] weather[ like]"
          - "weather"
          - "weather now"

      - sentences:
          - "<what_is>[ the] weather[ like] (for|in|at) <name>"
          - "<what_is>[ the] weather (for|in|at) <name>[ like]"
          - "<what_is>[ the] <name> weather[ like]"
        requires_context:
          domain: weather
