homeassistant:
  debug: true
  internal_url: !secret int_url
  external_url: !secret ext_url
  customize: !include_dir_named customize/
  packages: !include_dir_named packages/
  media_dirs:
    media: /config/www/media/
  whitelist_external_dirs:
    - /config/www/media/
    - /media/Frigate
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 172.30.33.0/24
        - 172.18.0.0/16
        - 192.168.3.0/24
      allow_bypass_login: true
    - type: homeassistant
http:
  #  ssl_certificate: /config/ssh_keys/homeassistant.pem
  #  ssl_key: /config/ssh_keys/homeassistant-key.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 172.30.33.0/24
    - 172.18.0.0/16
    - 192.168.3.0/24
  ip_ban_enabled: false
  login_attempts_threshold: 5
frontend:
  themes: !include_dir_merge_named themes/

default_config:
history:
ffmpeg:
wake_on_lan:
ssdp:
zeroconf:
smartir:

conversation:

scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml
shell_command: !include_dir_merge_named shell_commands/
template: !include_dir_merge_named template/
zone: !include zones.yaml
