###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Climate
#   @description    :   A Collection of Notification Scripts and Configs.
###############################################################################

automation:
  - id: 34c71e59-cd69-4481-b758-958807cf3537
    alias: Turn On Auto Climate Mode
    initial_state: true
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.climate_on_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.climate_automation

  - id: 04018017-1cb8-45e0-b81c-b4085a48908d
    alias: Turn Off Auto Climate Mode
    initial_state: true
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (state_attr('input_datetime.climate_off_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.climate_automation
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.climate_automation

script:
  bedroom_sterilization:
    alias: Turn on Sterilization Lamp for 30 min
    sequence:
      - service: notify.alexa_media_bedroom_speaker
        data:
          message: >
            {{ [
                    "Prepare for sterilization! The bedroom will be sanitized in 5 minutes.",
                    "Bedroom sterilization countdown initiated. Get ready for a clean and safe environment!",
                    "In 5 minutes, sterilization protocols for the bedroom will commence. Prepare accordingly.",
                    "Alert: Bedroom sterilization starting soon. Ensure the area is clear in 5 minutes.",
                    "Get ready for a refreshed space! Bedroom sterilization will begin in just 5 minutes.",
                    "Sterilization sequence initiated. The bedroom will be sanitized in 5 minutes. Clear the area.",
                    "Countdown to cleanliness: Bedroom sterilization starts in 5 minutes. Make necessary preparations."
                ] | random }}
      - service: script.text_notify
        data:
          title: Notification
          message: >
            {{ [
                    "Prepare for sterilization! The bedroom will be sanitized in 5 minutes.",
                    "Bedroom sterilization countdown initiated. Get ready for a clean and safe environment!",
                    "In 5 minutes, sterilization protocols for the bedroom will commence. Prepare accordingly.",
                    "Alert: Bedroom sterilization starting soon. Ensure the area is clear in 5 minutes.",
                    "Get ready for a refreshed space! Bedroom sterilization will begin in just 5 minutes.",
                    "Sterilization sequence initiated. The bedroom will be sanitized in 5 minutes. Clear the area.",
                    "Countdown to cleanliness: Bedroom sterilization starts in 5 minutes. Make necessary preparations."
                ] | random }}
      - delay:
          hours: 0
          minutes: 5
          seconds: 0
          milliseconds: 0
      - service: number.set_value
        data:
          value: "30"
        target:
          entity_id: number.uvfive_slmap2_2e5e_target_time
      - service: switch.turn_on
        data: {}
        target:
          entity_id:
            - switch.uvfive_slmap2_2e5e_radar_on
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.uvfive_slmap2_2e5e_switch_status
      - wait_for_trigger:
          - platform: state
            entity_id:
              - switch.uvfive_slmap2_2e5e_switch_status
            to: "off"
        timeout:
          hours: 0
          minutes: 40
          seconds: 0
          milliseconds: 0
      - service: notify.alexa_media_bedroom_speaker
        data:
          message: >
            {{ [
                "Good news! Bedroom sterilization is complete. You can now re-enter the sanitized space.",
                "The bedroom sterilization process has concluded successfully. Enjoy a clean and safe environment!",
                "Sterilization mission accomplished! The bedroom is now ready for use.",
                "All clear! Bedroom sterilization is finished. You may now resume normal activities.",
                "Sterilization complete: The bedroom is now free of contaminants. Welcome back!",
                "The bedroom sterilization process has finished. You can now enjoy a fresh and clean living space.",
                "Mission success: Bedroom sterilization is complete. Feel free to return to the sanitized room."
            ] | random }}
      - service: script.text_notify
        data:
          title: Notification
          message: >
            {{ [
                "Good news! Bedroom sterilization is complete. You can now re-enter the sanitized space.",
                "The bedroom sterilization process has concluded successfully. Enjoy a clean and safe environment!",
                "Sterilization mission accomplished! The bedroom is now ready for use.",
                "All clear! Bedroom sterilization is finished. You may now resume normal activities.",
                "Sterilization complete: The bedroom is now free of contaminants. Welcome back!",
                "The bedroom sterilization process has finished. You can now enjoy a fresh and clean living space.",
                "Mission success: Bedroom sterilization is complete. Feel free to return to the sanitized room."
            ] | random }}
    mode: restart
    icon: mdi:bug
