###############################################################################
#   @author         :   Jeffrey Stone
#   @date           :   02/19/2019
#   @package        :   Micebook
#   @description    :   A Collection of Presence Related Trackers and Sensors
###############################################################################
input_datetime:
  micebook_schedule:
    name: Micebook Schedule
    has_date: false
    has_time: true

input_select:
  micebook_wol:
    name: Micebook Control
    options:
      - None
      - Lock Screen
      - Suspend
      - Reboot
      - Shutdown
    initial: None
    icon: mdi:laptop

timer:
  micebook_timer:
    name: Micebook Timer
    duration: "00:15:00"
    icon: mdi:timer
    restore: true

automation:
  - id: 8a74e641-7155-4f86-827b-2390fa960d30
    alias: Micebook Control
    description: ""
    trigger:
      - platform: state
        entity_id:
          - input_select.micebook_wol
    condition: []
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.micebook_wol
                state: Lock Screen
            sequence:
              - service: shell_command.screen_lock_micebook
                metadata: {}
                data: {}
          - conditions:
              - condition: state
                entity_id: input_select.micebook_wol
                state: Suspend
            sequence:
              - service: shell_command.suspend_micebook
                metadata: {}
                data: {}
          - conditions:
              - condition: state
                entity_id: input_select.micebook_wol
                state: Reboot
            sequence:
              - service: shell_command.reboot_micebook
                metadata: {}
                data: {}
          - conditions:
              - condition: state
                entity_id: input_select.micebook_wol
                state: Shutdown
            sequence:
              - service: shell_command.turn_off_micebook
                metadata: {}
                data: {}
    mode: single

script:
