###############################################################################
#   @author         :   Jeffrey Stone
#   @date           :   02/19/2019
#   @package        :   Notify
#   @description    :   A Collection of Notification Scripts and Configs.
#                       Package modified from https://github.com/skalavala/smarthome/blob/master/packages/notify.yaml with inspiration
# 		                  from https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/script/speech_engine.yaml
###############################################################################

notify:
  - platform: ios
  - name: all_ios
    platform: group
    services:
      - service: mobile_app_jeffreys_iphone_11
      - service: mobile_app_jeffreys_ipad
      - service: mobile_app_iphone
      - service: mobile_app_skylars_ipad
  - name: parents_ios
    platform: group
    services:
      - service: mobile_app_jeffreys_iphone_11
      - service: mobile_app_jeffreys_ipad
      - service: mobile_app_iphone
  - name: jeff_ios
    platform: group
    services:
      - service: mobile_app_jeffreys_iphone_11
      - service: mobile_app_jeffreys_ipad
  - name: kat_ios
    platform: group
    services:
      - service: mobile_app_iphone
  - name: skylar_ios
    platform: group
    services:
      - service: mobile_app_skylars_ipad

  - name: twitter
    platform: twitter
    consumer_key: !secret twitter_consumer_key
    consumer_secret: !secret twitter_consumer_secret
    access_token: !secret twitter_access_token
    access_token_secret: !secret twitter_access_secret
  - name: twitter_js
    platform: twitter
    consumer_key: !secret twitter2_consumer_key
    consumer_secret: !secret twitter2_consumer_secret
    access_token: !secret twitter2_access_token
    access_token_secret: !secret twitter2_access_secret
  - name: twitter_sl
    platform: twitter
    consumer_key: !secret twitter3_consumer_key
    consumer_secret: !secret twitter3_consumer_secret
    access_token: !secret twitter3_access_token
    access_token_secret: !secret twitter3_access_secret
  - platform: alexa_media
    name: alexa_media
  - name: mastodon_sl
    platform: mastodon
    access_token: !secret mastodon_access_token
    client_id: !secret mastodon_client_id
    client_secret: !secret mastodon_client_secret
    base_url: https://mastodon.online
  - name: mastodon_mdl
    platform: mastodon
    access_token: !secret mdl_mastodon_access_token
    client_id: !secret mdl_mastodon_client_id
    client_secret: !secret mdl_mastodon_client_secret
    base_url: https://mastodon.online
  - name: mastodon_dev
    platform: mastodon_sl
    access_token: !secret test_mastodon_access_token
    client_id: !secret test_mastodon_client_id
    client_secret: !secret test_mastodon_client_secret
    base_url: https://mastodon.online

script:
  ###############################################################################
  # Txt Notify
  ###############################################################################
  text_debug:
    sequence:
      - condition: state
        entity_id: input_boolean.debug_texts
        state: "on"
      - service: notify.jeff_ios
        data_template:
          message: >
            {{ message }}

  text_notify:
    fields:
      who:
        selector:
          text:
        name: who
        required: true
      title:
        selector:
          text:
        name: title
        required: false
      message:
        selector:
          text:
        name: message
        required: true
    sequence:
      - condition: state
        entity_id: input_boolean.text_notifications
        state: "on"
      - choose:
          - conditions:
              - condition: template
                value_template: '{{ who == "jeff"}}'
              - condition: state
                entity_id: input_boolean.text_notify_jeff
                state: "on"
            sequence:
              - service: notify.jeff_ios
                data:
                  title: "{{ title }}"
                  message: "{{ message }}"
          - conditions:
              - condition: template
                value_template: '{{ who == "kat"}}'
              - condition: state
                entity_id: input_boolean.text_notify_kat
                state: "on"
            sequence:
              - service: notify.kat_ios
                data:
                  title: "{{ title }}"
                  message: "{{ message }}"
          - conditions:
              - condition: template
                value_template: '{{ who == "skylar"}}'
              - condition: state
                entity_id: input_boolean.text_notify_skylar
                state: "on"
            sequence:
              - service: notify.skylar_ios
                data:
                  title: "{{ title }}"
                  message: "{{ message }}"
          - conditions:
              - condition: template
                value_template: '{{ who == "parents"}}'
              - condition: state
                entity_id: input_boolean.text_notify_parents
                state: "on"
            sequence:
              - service: notify.parents_ios
                data:
                  title: "{{ title }}"
                  message: "{{ message }}"
        default:
          - service: notify.all_ios
            data:
              title: "{{ title }}"
              message: "{{ message }}"

  text_alert:
    sequence:
      - service: >
          {% if who == 'jeff' %}
            notify.jeff_ios
          {% elif who == 'kat' %}
            notify.kat_ios
          {% elif who == 'skylar' %}
            notify.skylar_ios
          {% elif who == 'parents' %}
            notify.parents_ios
          {% else %}
            notify.all_ios
          {% endif %}
        data:
          title: "{{ title }}"
          message: "{{ message }}"
          #data:
          #   attachment:
          #     url: '{{ url }}'
          #     content-type: '{{ content_type }}'
          #     hide-thumbnail: false
          #  push:
          #     sound: '{{ ios_sound }}'
          #    badge: 0
          #     category: '{{ ios_category }}'
          #   entity_id: '{{ camera_entity }}'

  text_alert_image:
    sequence:
      - service: >
          {% if who == 'jeff' %}
            notify.jeff_ios
          {% elif who == 'kat' %}
            notify.kat_ios
          {% elif who == 'skylar' %}
            notify.skylar_ios
          {% elif who == 'parents' %}
            notify.ios_parents
          {% else %}
            notify.all_ios
          {% endif %}
        data:
          title: "{{ title }}"
          message: "{{ message }}"
          data:
            attachment:
              url: "{{ url }}"
              content-type: "{{ content_type }}"
              hide-thumbnail: false
          #  push:
          #     sound: '{{ ios_sound }}'
          #    badge: 0
          #     category: '{{ ios_category }}'
          #   entity_id: '{{ camera_entity }}'
