- id: door_notifications
  alias: Door Notifications
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.front_door_contact
        - binary_sensor.kitchen_door_contact
        - binary_sensor.basement_door_contact
        - binary_sensor.back_door_contact
        - binary_sensor.garage_door
      to: "on"
      id: chime
    - platform: state
      entity_id:
        - binary_sensor.front_door_contact
        - binary_sensor.kitchen_door_contact
        - binary_sensor.basement_door_contact
        - binary_sensor.back_door_contact
        - binary_sensor.basement_access_door
      from: "off"
      to: "on"
      for: 00:01:00
      id: door_still_open
  condition:
    - condition: state
      entity_id: input_boolean.audible_notifications
      state: "on"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: chime
            - condition: or
              conditions:
                - condition: state
                  entity_id: media_player.ha_blue
                  state: idle
                - condition: state
                  entity_id: media_player.ha_blue
                  state: "off"
          sequence:
            - service: media_player.volume_set
              data_template:
                entity_id: media_player.ha_blue
                volume_level: 0.2
            - service: media_player.play_media
              entity_id: media_player.ha_blue
              data:
                media_content_id: https://slackerlabs.s3.amazonaws.com/audio/notifications/door_open.wav
                media_content_type: music
        - conditions:
            - condition: trigger
              id: door_still_open
          sequence:
            - service: script.speech_engine
              data:
                message:
                  "The {{ trigger.to_state.attributes.friendly_name }} {{ [\n  '
                  is standing open.',\n  ' is open.',\n  ' does not close on its own.',\n
                  \ ' was left standing open.'\n] | random }} {{ [\n    'Can a human be
                  so kind and close it?',\n    'The air quality in this house has actually
                  improved.',\n    'Closing the door would improve the internal climate
                  of the house.',\n    'Hey. The door was just opened and this is crazy.
                  But now you know. So close it maybe.',\n    'If at first you do not succeed
                  in closing the door, please try again. Like, Right now seems like a good
                  time to try again.',\n    'And the automatic door closer appears to be
                  broken. So, you know what to do. Time to get physical.',\n    'I would
                  close it for you. But I lack legs. And Arms.'\n] | random }}\n"
  initial_state: true

- id: motion_detected_front_door
  alias: Motion Detected Front Door
  trigger:
    - platform: state
      entity_id: binary_sensor.aarlo_motion_front_door
      from: "off"
      to: "on"
  action:
    - service: image_processing.scan
      entity_id: image_processing.doods_aarlo_front_door
    - choose:
        - conditions:
            - condition: template
              value_template:
                '{{ states("image_processing.doods_aarlo_front_door") | int
                > 0 }}'
          sequence:
            - service: mqtt.publish
              data:
                topic: house/front_door_motion/away_count
                payload_template:
                  "{{ states.sensor.front_door_motion_away_count.state |
                  int + 1 }}"
                retain: true
            - service: script.status_annc
              data:
                who: "{{ states.sensor.room_presence.state }}"
                call_interuption: 1
                call_snark_door_motion: 1
                speech_message:
                  '{{ [ "I have detected someone at the ", "Someone appears
                  to be at the ", "There is a person at the ", "My sensors are picking up
                  presence at the ", "We appear to have a visitor at the ", "My sensors
                  have detected a meat popsicle at the " ] | random }} {{ trigger.to_state.attributes.friendly_name
                  }}'
    - delay:
        minutes: 2
  initial_state: true
