- id: '1711677483711'
  alias: Turn Off Laundry Day
  description: ''
  trigger:
  - platform: tag
    tag_id: 20624072-f14c-4a2d-b2ae-9214dbbb5ecb
  condition:
  - condition: state
    entity_id: calendar.laundry
    attribute: message
    state: Laundry Day
  action:
  - service: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.laundry_helper
  - service: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.laundry_pickup
  - service: script.speech_engine
    data:
      message: "{{ [\n    'Welcome home! Do not forget to put away your freshly picked-up
        laundry in the wardrobe',\n    'Back home with fresh laundry! Time to put
        it away in the wardrobe and enjoy the freshness',\n    'Welcome back! Your
        freshly picked-up laundry is waiting for you to put it in the wardrobe',\n
        \   'Home sweet home! Remember to organize your freshly picked-up laundry
        in the wardrobe',\n    'Welcome back, laundry hero! Put your freshly picked-up
        clothes in the wardrobe and enjoy',\n    'Back from the laundry journey! It
        is time to put away your clean clothes in the wardrobe',\n    'Welcome home,
        freshness awaits! Do not forget to organize your laundry in the wardrobe',\n
        \   'Welcome back! Your laundry mission is complete, now remember to put it
        in the wardrobe',\n    'Home at last! Remember to put your freshly picked-up
        laundry in the wardrobe for freshness',\n    'Welcome back, laundry conqueror!
        Time to put away your clean clothes in the wardrobe'\n] | random }}\n"
  mode: restart
- id: '1713940163943'
  alias: Mastodon Ad Posting
  description: ''
  trigger:
  - platform: calendar
    event: start
    offset: '12:0:0'
    entity_id: calendar.mastodon
  condition:
  - condition: state
    entity_id: calendar.mastodon
    attribute: message
    state: Ad
  action:
  - service: script.mastodon_ad
    metadata: {}
    data: {}
  mode: restart
- id: '1713940222818'
  alias: Mastodon Shark Post
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  - platform: time
    at: '14:00:00'
  - platform: time
    at: '18:00:00'
  condition: []
  action:
  - service: script.mastodon_snark
    metadata: {}
    data: {}
  mode: single
- id: '1714126208361'
  alias: Mastodon Stat Post
  description: ''
  trigger:
  - platform: time
    at: '12:00:00'
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - service: script.mastodon_stats
    data: {}
  mode: single
- id: '1714190358197'
  alias: Mastodon Weather Post
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  - platform: time
    at: '10:00:00'
  - platform: time
    at: '13:00:00'
  - platform: time
    at: '16:00:00'
  - platform: time
    at: '19:00:00'
  - platform: time
    at: '22:00:00'
  - platform: time
    at: 01:00:00
  - platform: time
    at: 04:00:00
  condition: []
  action:
  - service: script.mastodon_weather
    metadata: {}
    data: {}
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: script.mastodon_space_weather
    metadata: {}
    data: {}
  mode: restart
- id: '1714358939598'
  alias: Climate Auto Control
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.climate_automation
    to: 'off'
    from: 'on'
    id: climate_off
  - platform: state
    entity_id:
    - input_boolean.climate_automation
    to: 'on'
    from: 'off'
    id: climate_on
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - climate_on
      sequence:
      - service: climate.set_hvac_mode
        metadata: {}
        data:
          hvac_mode: dry
        target:
          entity_id: climate.bedroom_aircon
    - conditions:
      - condition: trigger
        id:
        - climate_off
      sequence:
      - service: climate.set_hvac_mode
        metadata: {}
        data:
          hvac_mode: 'off'
        target:
          entity_id: climate.bedroom_aircon
  mode: single
- id: '1714569609969'
  alias: Awtrix current playing song
  description: ''
  use_blueprint:
    path: homeassistant/awtrix_spotify.yaml
    input:
      awtrix_light: 4c7efdc44c80355d417605701646c757
      media_player: media_player.spotify_simplemice
      text_color:
      - 208
      - 0
      - 250
      icon_in: '18207'
- id: '1715135148977'
  alias: Awtrix Weather Forecast
  description: ''
  use_blueprint:
    path: homeassistant/awtrix_weather_app.yaml
    input:
      awtrix_displays:
      - 4c7efdc44c80355d417605701646c757
      toggle_helper: input_boolean.awtrix_weather
      my_sensor: weather.openweathermap
      text_color:
      - 200
      - 0
      - 255
      switch_to_app: true
      scrollspeed: 50
- id: '1715157720144'
  alias: Porch Motion Lights
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.porch_motion
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.porch_motion
        state: 'on'
      sequence:
      - service: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.porch_bulb
    - conditions:
      - condition: state
        entity_id: binary_sensor.porch_motion
        state: 'off'
      sequence:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.porch_bulb
  mode: single
- id: '1715172273118'
  alias: Mastodon Gas Price Posting
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  - platform: time
    at: '16:00:00'
  condition: []
  action:
  - service: script.mastodon_gasoline
    metadata: {}
    data: {}
  mode: single
- id: '1715178071678'
  alias: Telegram Phuket Weather Post
  description: ''
  trigger:
  - platform: time
    at: 09:55:00
  condition: []
  action:
  - service: script.telegram_auto_weather
    metadata: {}
    data: {}
  mode: single
- id: '1715179083522'
  alias: Telegram Gas Price Posting
  description: ''
  trigger:
  - platform: time
    at: 09:10:00
  condition: []
  action:
  - service: script.telegram_gasoline
    data: {}
  mode: single
- id: '1715182243826'
  alias: Awtrix Gas Price
  description: ''
  use_blueprint:
    path: homeassistant/awtrix_create_sensor_app.yaml
    input:
      switch_to_app: true
      my_template_sensor: Gasohol 91 - {{ states('sensor.gas_91_price_ptt')}} THB
        and Gasohol 95 {{ states('sensor.gas_95_price_ptt')}} THB
      awtrix_displays:
      - 4c7efdc44c80355d417605701646c757
      my_sensor: sensor.gas_91_price_ptt
      text_color:
      - 251
      - 0
      - 255
      toggle_helper: input_boolean.awtrix_gasoline
- id: '1715226672662'
  alias: Awtrix Rain
  description: ''
  use_blueprint:
    path: homeassistant/awtrix_rain_forecast.yaml
    input:
      awtrix_displays:
      - 4c7efdc44c80355d417605701646c757
      toggle_helper: input_boolean.awtrix_rain
      my_sensor: weather.openweathermap
      graph_color:
      - 212
      - 0
      - 255
      my_text: No rain
      switch_to_app: true
      graph_type: bar
      duration: '0'
- id: '1715409461677'
  alias: Work Mode Alarm
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.work_mode
    to: 'on'
    id: work_on
  - platform: state
    entity_id:
    - input_boolean.work_mode
    to: 'off'
    id: work_off
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - work_on
      sequence:
      - service: scene.create
        metadata: {}
        data:
          scene_id: before_work_alarm
          snapshot_entities:
          - light.closet_lamp
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
      - service: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 255
          - 0
          - 0
          brightness_pct: 100
        target:
          entity_id: light.closet_lamp
      - repeat:
          sequence:
          - service: script.speech_engine
            data:
              message: "{{ [\n    \"Bright and Early Alert: Time to put on your work
                hat. Remember, your cosy bed is anticipating your return later.\",\n
                \   \"Go-Getter Reminder: It's your signal to get ready for work.
                Your lazy morning routine is on a short hiatus.\",\n    \"Hustle Call:
                From the comfort of home to the thrill of work, it's transition time.
                Fear not, your favourite breakfast cereals will be safe.\",\n    \"Ready,
                Steady, Work! Time to bring out your professional persona. Your yoga
                mat is content and ready for some alone time.\",\n    \"Work Time
                Alert: Your workspace misses you. The houseplants have agreed to keep
                each other company.\",\n    \"Productivity Push: It's time to conquer
                the workday. Your comfy slippers are planning a secret meeting with
                the doormat.\",\n    \"Break Dawn, Make Haste: Time to exchange sweet
                dreams for real achievements. Your home workout gear is looking forward
                to a quiet morning.\",\n    \"Rise and Grind Notice: Time to swap
                your bed for the desk. Meanwhile, your hobby supplies are negotiating
                an extended break.\",\n    \"Action-Packed Day Ahead: Let's get you
                prepared for work. Your favourite book promises not to reveal the
                ending until you finish work.\",\n    \"Professional Pursuit Reminder:
                Get set, work's awaiting. Your cosy throw blanket is planning to do
                some self-care today.\",\n    \"Early Riser Alert: It's time to get
                ready for work. Keep in mind, your dreams need timeout to plan your
                success.\",\n    \"Saddle Up Reminder: Get ready to hustle, the office
                chair is waiting for you. It's been reported missing your company.\",\n
                \   \"Shift Swap Alert: Time to transfer from couch control to office
                operations. Your living room confirmed it can handle absence management.\",\n
                \   \"Wake Up Call: Rise and shine for work. Your pillow suggests
                that it needs some 'me-time'.\",\n    \"Out of Comfort Zone Alert:
                Time to swap pyjamas for work attire. Fasten your motivation seatbelts.\",\n
                \   \"Morning Jumpstart: Let's put the home shenanigans on snooze
                and launch the workday. Your cat promises some funny anecdotes later.\",\n
                \   \"Get-Up Notification: Let's roll up your sleeves and dig into
                the workday. Your pet plants requested a day of 'photosynthesis tranquility'.\",\n
                \   \"Start of Connect: Time to plug in the workstation. Your favorite
                TV show confirmed it won't start a new episode without you.\",\n    \"Operation
                Start: Rise for another challenging yet exciting day at work. Your
                morning newspaper wishes to read itself today.\",\n    \"Let's Hustle
                Reminder: Time to dive into the work pool. Your home slippers decided
                they need a spa day.\",\n    \"Reminder: It is time to get ready for
                work. Donot forget to bid your coffee adieu\",\n    \"Attention: Time
                to prepare for work. Leave your sense of humor at home it tends to
                work overtime\",\n    \"It is time to swap the cozy couch for the
                office chair. BTW, your cat is already eyeing your spot\",\n    \"Get-ready
                alert Time to prep for work. Coffee into the thermos, and off you
                go! Yes, your cat finds this amusing\",\n    \"Donot forget: It is
                time for work. And yes, your coffee claims it doesnot know you\",\n
                \   \"Maintenance reminder: Time to get ready for work. Your coffee
                asked not to be disturbed until tomorrow\",\n    \"Consumable status:
                It's time to head to work. Do recall that your coffee prefers to stay
                home\"\n] | random }}\n"
          - delay:
              hours: 0
              minutes: 1
              seconds: 0
              milliseconds: 0
          while:
          - condition: state
            entity_id: input_boolean.work_mode
            state: 'on'
    - conditions:
      - condition: trigger
        id:
        - work_off
      sequence:
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.before_work_alarm
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: scene.reload
        metadata: {}
        data: {}
  mode: single
- id: '1715440619474'
  alias: Test Back Home Light On
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.simplemice
    to: home
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.porch_bulb
      state: 'on'
    - condition: sun
      before: sunrise
      after: sunset
  action:
  - service: scene.turn_on
    target:
      entity_id:
      - scene.lamp
      - scene.kitchen_ambient
    data: {}
  mode: single
- id: '1715521277578'
  alias: Test Light After Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: +0:10:00
  condition:
  - condition: state
    entity_id: person.simplemice
    state: home
  action:
  - service: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.kitchen_ambient
  - service: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.lamp
  mode: single
- id: '1715922054256'
  alias: Telegram Mastodon Phuket BirdNet
  description: ''
  trigger:
  - platform: time
    at: '22:01:00'
  condition: []
  action:
  - service: script.telegram_auto_birdnet
    metadata: {}
    data: {}
  - service: script.mastodon_birds
    metadata: {}
    data: {}
    enabled: true
  mode: single
- id: '1716002601688'
  alias: Teleram Phuket Holidays
  description: ''
  trigger:
  - platform: calendar
    event: start
    offset: '8:30:0'
    entity_id: calendar.holidays_in_thailand
  condition: []
  action:
  - service: script.telegram_auto_holidays
    metadata: {}
    data: {}
  mode: single
