homeassistant:
  internal_url: http://192.168.3.2:8123
  external_url: !secret ext_url
  customize: !include customize.yaml
  packages: !include_dir_named packages
  media_dirs:
    media: /config/www/media/
  whitelist_external_dirs:
    - /config/www/camera_snaps/
    - /config/www/media/
    - /config/www/media/images/
    - /config/www/tweet_images/
    - /config/www/plates/
    - /config/www/birds/
    - /config/www/
    - /config/www/doods/
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.3.0/24
      allow_bypass_login: true
    - type: homeassistant

default_config:
history:
ffmpeg:
wake_on_lan:
conversation:
ssdp:
zeroconf:
python_script:

http:
  #  ssl_certificate: /config/ssh_keys/homeassistant.pem
  #  ssl_key: /config/ssh_keys/homeassistant-key.pem
  use_x_forwarded_for: true
  ip_ban_enabled: false
  login_attempts_threshold: 5
  trusted_proxies:
    - 172.30.0.0/24
    - 192.168.3.0/24

frontend:
  themes: !include_dir_merge_named themes/

#lovelace:
#  mode: storage
# Add yaml dashboards
#  dashboards:
#    tablet-yaml:
#      mode: yaml
#      title: Tablet
#      icon: mdi:tablet-dashboard
#      show_in_sidebar: true
#      filename: monitor-ui-dashboard.yaml

scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml
shell_command: !include_dir_merge_named shell_commands
device_tracker: !include_dir_merge_list device_tracker
