- id: '1714547712381'
  name: Closet Light
  entities:
    light.closet_lamp:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 63.75
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 286
      - 100
      rgb_color:
      - 195
      - 0
      - 255
      xy_color:
      - 0.306
      - 0.118
      icon: mdi:lamp
      friendly_name: Сloset Lamp
      supported_features: 0
      state: 'on'
    light.livingroom_closet_ambient:
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - xy
      effect:
      color_mode: xy
      brightness: 255
      hs_color:
      - 180.235
      - 100
      rgb_color:
      - 0
      - 254
      - 255
      xy_color:
      - 0.151
      - 0.342
      icon: mdi:led-strip
      friendly_name: Livingroom Closet Ambient
      supported_features: 44
      state: 'on'
  icon: mdi:lamp
  metadata:
    light.closet_lamp:
      entity_only: true
    light.livingroom_closet_ambient:
      entity_only: true
- id: '1715167044111'
  name: Kitchen Ambient On
  entities:
    light.downstair_kitchen_ambient:
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - xy
      friendly_name: Kitchen Ambient
      supported_features: 44
      color_mode: xy
      brightness: 255
      hs_color:
      - 308.941
      - 100
      rgb_color:
      - 255
      - 0
      - 217
      xy_color:
      - 0.437
      - 0.178
      state: 'on'
    light.kitchen_closet_ambient:
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - xy
      friendly_name: Kitchen Closet Ambient
      supported_features: 44
      color_mode: xy
      hs_color:
      - 172.913
      - 99.608
      rgb_color:
      - 1
      - 255
      - 225
      xy_color:
      - 0.154
      - 0.392
      brightness: 255
      state: 'on'
  icon: mdi:led-strip
  metadata:
    light.downstair_kitchen_ambient:
      entity_only: true
    light.kitchen_closet_ambient:
      entity_only: true
- id: '1715623981949'
  name: Closet Off
  entities:
    light.livingroom_closet_ambient:
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - xy
      effect:
      color_mode:
      brightness:
      hs_color:
      rgb_color:
      xy_color:
      icon: mdi:led-strip
      friendly_name: Livingroom Closet Ambient
      supported_features: 44
      state: 'off'
    light.closet_lamp:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - hs
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      icon: mdi:lamp
      friendly_name: Сloset Lamp
      supported_features: 0
      state: 'off'
  icon: mdi:led-strip
  metadata:
    light.livingroom_closet_ambient:
      entity_only: true
    light.closet_lamp:
      entity_only: true
- id: '1715624046875'
  name: Kitchen Ambient Off
  entities:
    light.downstair_kitchen_ambient:
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - xy
      friendly_name: Kitchen Ambient
      supported_features: 44
      color_mode:
      brightness:
      hs_color:
      rgb_color:
      xy_color:
      state: 'off'
    light.kitchen_closet_ambient:
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - xy
      friendly_name: Kitchen Closet Ambient
      supported_features: 44
      color_mode:
      hs_color:
      rgb_color:
      xy_color:
      brightness:
      state: 'off'
  icon: mdi:led-strip
  metadata:
    light.downstair_kitchen_ambient:
      entity_only: true
    light.kitchen_closet_ambient:
      entity_only: true
