sp_dc: ""
sp_key: ""

ext_url: ""

coinmarketcap_curl: ""

todolist_authorization: ""
todolist_project: ""

git_exporter_user: ""
git_exporter_pass: ""

todoist_token: ""

dev_track_xiaomi_hub: ""

tg_group: ""
tg_me: ""
tg_api: ""

living_remote: ""
bedroom_remote: ""

17login: ""
17pass: ""

mouse: ""

openweather_all: ""

aqoo: ""

db_link: ""

#poly_key: ""
#poly_id: ""
poly_key: ""
poly_id: ""

platerecognizer: ""

eth_wallet: ""

weather_long: ""
weather_lat: ""

home_long: ""
home_lat: ""

alarm_code: ""

tides: ""

pialert: ""

#####
#twitter
tw_consumer_key: ""
tw_consumer_secret: ""
tw_access_token: ""
tw_access_secret: ""
tw_username: ""

mastodon_access_token: ""
mastodon_client_id: ""
mastodon_client_secret: ""

mastodon_access_token1: ""
mastodon_client_id1: ""
mastodon_client_secret1: ""
