language: en
responses:
  intents:
    HassTurnOff:
      default: "Turned off the {{ state.domain }}"
      lights_area: "Turned off the lights"
      fans_area: "Turned off the fans"
      cover: "Closed"
      light_all: "Turned off all of the lights"
      fan_all: "Turned off all of the fans"
      cover_device_class: "Closed the {{ slots.device_class }}"
      lock: "Unlocked"
      valve: "Closed"
