###############################################################################
#   @author         :   Simplemice
#   @date           :   19/08/2025 (updated 22/08/2025, revised 31/08/2025)
#   @package        :   Recorder
#   @description    :   Recorder Settings
###############################################################################

recorder:
  purge_keep_days: 7
  auto_purge: true
  purge_interval: 1
  commit_interval: 30

  # If you stay on SQLite, at least don’t abuse it
  db_url: sqlite:////config/home-assistant_v2.db

  include:
    domains:
      - sensor
      - binary_sensor
      - person
      - device_tracker
      - switch
      - light

    entity_globs:
      - sensor.*_energy
      - sensor.*_power
      - sensor.*_temperature
      - sensor.*_humidity

  exclude:
    entity_globs:
      - sensor.*_signal_strength
      - sensor.*_rssi
      - sensor.*_linkquality
      - sensor.*_uptime
      - sensor.*_last_seen
      - sensor.*_battery*
      - sensor.*_voltage*
      - sensor.*_free_memory
      - sensor.*_heap*
      - sensor.*_loop*
      - sensor.*_internal*
      - sensor.*_debug*
      - sensor.*_illuminance_raw
      - sensor.*_pressure_raw
      - binary_sensor.*_availability

    domains:
      - updater
      - persistent_notification
      - automation
      - script

logger:
  default: warning
